### ISSUE TITLE
[469a] TacticalOps - Scoreboard and buy window misaligned.

### ISSUE THREAD

**Issue by krisudxc** [OldUnreal/UnrealTournamentPatches#10]
Scoreboard and buy window misaligned. 
Mouse out of sync in buy and voting menu meaning object such as map or gun is highlighted when mouse cursor isn't on top of it.
These issues do not occur with every client. 

Attached screenshot showing the issue
![Shot00003](https://user-images.githubusercontent.com/66308397/94024673-6186e500-fdc0-11ea-8033-a67df421ffc0.png)

**Comment by CacoFFF** [comment]
Is "Override Font Scaling" option disabled?

**Comment by krisudxc** [comment]
I'm not able to set "Override Font Scaling" because the game is tactical ops.
In order to use v469a on Tacops I need to preserve original botpack.u and UTmenu.u. I believe this setting is in UTmenu.u.
Is there way I can set/unset this directly in .ini?

**Comment by krisudxc** [comment]
I figured it out. This is probably just TO specific thing.
To fix this for those having issues change AutoGUIScale to false like below.
[TOSystem.TO_RootWindow]
bTORetail=True
GUIScale=0.800000
LookAndFeelClass=UMenu.UMenuMetalLookAndFeel
ConfiguredGUIScale=1.000000
AutoGUIScale=False

**Comment by stijn-volckaert** [comment]
I'm going to close this issue since we will not be able to fix this problem ourselves. It looks like TO would need to be updated instead

**Comment by stijn-volckaert** [comment]
Some additional information that might be helpful to anyone willing to update TO: This happens because of how UT implements GUI Scaling. With GUI Scales above 1.0, the UWindow coordinate system no longer matches the canvas coordinate system.

If you run your game at 1920x1080 and you have GUIScale set to 2.0, a fullscreen UWindow would have a resolution of (1920x1080)/GUIScale. In this case, this would be 960x540. Your Canvas would still have 1920x1080 as its resolution, however.

When rendering a UWindow, the UWindow base functions convert from UWindow coordinates to Canvas coordinates by multiplying all coordinates and sizes with the GUI Scale. Thus, as long as you don't call Canvas functions directly from a custom UWindow, you need not worry about the GUI Scale at all. UWindow will handle all conversions for you.

If you _do_ call Canvas functions such as TextSize, SetPos, DrawText, DrawTile, DrawIcon, etc. directly, you need to convert from UWindow coordinates to Canvas coordinates yourself. I just did this myself for another game mod of roughly the same size and complexity as TO and it took me about 2 hours of work.

**Comment by guitronimo** [comment]
In TO it kind of requires to completely rework the HUD and replacing it by a more modern version. Unfortunately you cannot just extend from the s_HUD because then TOST wont work with that updated classes. 

If there is a real need for improvement i can see if i can update TOST instead. But TO comes in 2 versions and for both versions TOST is very different. 

Thanks for addressing this and for the information about the coordinates. Its helpful information.

Cheers, LuckyDog
