### ISSUE TITLE
[469c] Add Unreal 227j Shadows support

### ISSUE THREAD

**Issue by AtifArshad1995** [OldUnreal/UnrealTournamentPatches#1015]
I really like the object/players shadows introduced in Unreal 227j. Probably might be too big of a request for 469c (since it is already in RC stage), but perhaps for 469d.

**Comment by Calinou** [comment]
> I really like the object/players shadows introduced in Unreal 227j.

Didn't 227i also have those shadows? The default is blob shadows, but you can select between 3 shadow mapping qualities.

That said, for Unreal Tournament, being able to see more shadows than in the vanilla game could be problematic from a competitive perspective.

**Comment by stijn-volckaert** [comment]
I like that feature too, but we promised not to change the look and feel of the game with our patches. By adding higher-quality shadow rendering, we would clearly break that promise.

**Comment by SeriousBuggie** [comment]
Agree. Also want add few notes:
As mention above shadows also can provide advantages in network play.
In single play shadows can reveal some stuff, which not visible in other way.
I play In Borderlands recently. There dynamic shadows in much more modern UnrealEngine.
On map usually present movable objects which drop shadows. But when this objects behind you, they stop animate, for save CPU. Usually this is not noticeable. But shadows allow you see what happen on back, and you really notice this effect.
So shadows goes reveal more things from it can be before.
On local play this mean you can see frozen animation optimization.
On network play you can see how relevance work sometimes, since need alter relevance for proper handle things.
In fact you need make actor relevant to player, if player able see actor shadow. 
Determine such is hard and can greatly increase count of relevant actors. So this can lead to channels overflow there not be it before.
If you not do relevance alteration, then possible suddenly appear shadows from actors replicated too late.

So if it is been even consider to implement this feature (which is not), it is more hard properly implement in UT rather from Unreal, just because UT more net play related.
