### ISSUE TITLE
[469b] UnrealED. Panning/rotating view in 3d viewport spazzes out frequently 

### ISSUE THREAD

**Issue by Vossn** [OldUnreal/UnrealTournamentPatches#1026]
When using the right mouse button to look around in UED, the view spazzes/skips/jumps very frequently.

It goes normal speed - split second hyper speed - normal speed again.

**Comment by BerserkerBG** [comment]
> When using the right mouse button to look around in UED, the view spazzes/skips/jumps very frequently.
> 
> It goes normal speed - split second hyper speed - normal speed again.

I have same issue. This is because Unreal Ed cant handle 1000 or 500 mouse polling rate. When I use Ued I switch my mouse polling rate to 250 and seems to fix it. After im done with Ued I switch my mouse back to 1000 polling rate. Very annoying and I have to do it manually from GUI every time, because my mouse cant bind polling rate changes.

![Screenshot_58](https://user-images.githubusercontent.com/58362332/187096232-681c209e-a943-403d-a650-d3c99bf6ff9e.png)

**Comment by mlhenson** [comment]
I'm currently seeing this same behavior in UnrealEd on 469c. When my mouse (Logitech G502 Lightspeed) is set to 1000hz polling I get the skipping/jumping when attempting to use the mouse to navigate any of the viewports. Bumping it down to 250hz polling resolves this issue. 

Didn't observe this issue when I was working in 469b a few months ago and rolling back to 469b and doing a quick test in the editor, I'm unable to reproduce the issue even when at 1000hz.

**Comment by BerserkerBG** [comment]
> Didn't observe this issue when I was working in 469b a few months ago and rolling back to 469b and doing a quick test in the editor, I'm unable to reproduce the issue even when at 1000hz.

It is also present on 469a and 469b, but it didn't happen as frequent. For example, It was happening once at random times when I was mapping constantly for 2 hours. And in 469c its much worse - it basically happens every 5-10 minutes and makes Ued pretty much unusable.

**Comment by stijn-volckaert** [comment]
469d will allow you to use raw input in UnrealEd. This will fix the issue for high-dpi mice
