### ISSUE TITLE
Palette Botpack.Skins.Palette413 error happening quite often

### ISSUE THREAD

**Issue by An0th3rOne** [OldUnreal/UnrealTournamentPatches#1079]
have been getting the above error from players trying to connect to server on quite a few occasions.
![Palette Botpack Skins Palette413](https://user-images.githubusercontent.com/24214072/192139065-45763e99-0b84-4581-856a-79dc71445ed1.png)
never had this error before.. also happened on 469b.

**Comment by SeriousBarbie** [comment]
Looks like a file mismatch. See also [UT99.org](https://ut99.org/viewtopic.php?f=12&t=12858).
Or/and related to https://github.com/OldUnreal/UnrealTournamentPatches/issues/51

**Comment by SeriousBuggie** [comment]
Need more info. What server version. What client. AFAIK @CacoFFF ask for tell him such stuff if this happen. He his few similar problems in conform packages.

**Comment by An0th3rOne** [comment]
469 clients so far , also happens randomly , sometimes fine other times error palette.
server running 469c rc4

**Comment by An0th3rOne** [comment]
This is happening when UltimateNewNet is loaded on server.. so that could be cause.

**Comment by An0th3rOne** [comment]
![Discord_onEWD26HK7](https://user-images.githubusercontent.com/24214072/192241740-d7c9c085-c72c-48c0-a45b-ff91f85acb05.png)

**Comment by An0th3rOne** [comment]
this error happens when 469a clients try to connect to server while UN1m is loaded.

**Comment by stijn-volckaert** [comment]
This happened because the ucc conform commandlet (which we use to ensure unrealscript packages remain network compatible with prior versions) did not conform palette names properly. We fixed the issue in 469b, though, so these clients should simply upgrade to 469b.

**Comment by dov910** [comment]
Authors please preserve the old palette names, because editing 1000 of package is not possible, but I can fix this for UltimateNewNet, I also fixed this issue for Monster Match.

**Comment by An0th3rOne** [comment]
might write a little blurb on ut99.org later to this effect so that if anyone googles Palette Error UT99 there's an answer for them

**Comment by An0th3rOne** [comment]
https://ut99.org/viewtopic.php?f=12&t=15440

**Comment by CacoFFF** [comment]
A bit of history:

I found the issue because of dynamic textures (scripted, water, etc) in Siege and some other mods, if you create a texture that references something from Botpack, UnrealI, etc rather than a .utx package, you'll end up loading the texture's palette as well.

The problem with that is that when you rebuild any of the original .u packages, the palette names will get scrambled.
This issue was already happening with some v436 clients as well (especially the ones with japanese or hacked/cheat UT's).

To avoid palette name scrambling I added a new functionality to package conform where all textures in the new version will have their palettes renamed to the same names as the palettes from the old version (that involves a lot of name swapping).

As @stijn-volckaert mentioned, the new batch of fixed packages didn't come until v469b so anyone using UT v469a (or the betas) will have problems joining either v436, v451 or v469b/c servers where palettes are referenced.

Simply, have all clients upgrade to v469b.
