### ISSUE TITLE
Net client crash while joining server running map "MH-(dU)AS-ImperialBaseFinal"

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1116]
Server "Barbiesworld" (64 bit Linux, 469c-RC4) was running the map "MH-(dU)AS-ImperialBaseFinal" and clients (here 469c) crashed when joined:
> Critical: appError called:
Critical: Assertion failed: Frame->Level->Model->Points.Num()<=MAX_POINTS [File:C:\GameDev\UnrealTournament\Render\Src\UnRender.cpp] [Line: 1535]
Critical: Windows GetLastError: Zur Verarbeitung dieses Befehls sind nicht genügend Speicherressourcen verfügbar. (8)
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing UWindowsClient::ShutdownAfterError
Exit: ALAudio subsystem shut down.
Exit: UALAudioSubsystem::ShutdownAfterError
Log: DirectDraw End Mode
Exit: UD3D9RenderDevice::ShutdownAfterError
Critical: URender::OccludeBsp
Critical: URender::OccludeFrame
Critical: URender::DrawWorld
Critical: UGameEngine::Draw
Critical: UWindowsViewport::Repaint
Critical: UWindowsClient::Tick
Critical: ClientTick
Critical: UGameEngine::Tick
Critical: UpdateWorld
Critical: MainLoop
Exit: Exiting.
Log: Log file closed, 11/07/22 12:11:30

![ClientCrashOnMH-(dU)AS-ImperialBaseFinal](https://user-images.githubusercontent.com/81397053/200312096-057bf295-f07f-44a2-a0cd-ebbeba006c4c.jpg)

Server's log didn't show any unusual except 94 times this message after players try to join:
> Connection timed out after 15.000000 seconds (15.03XXXX)

(XXXX digits vary)

Sadly I didn't try with older client versions nor I could reproduce this error on my test server (Linux 32 bit,  469c-RC4) .

**Comment by SeriousBarbie** [comment]
I got the message that crash also happened with a 436 client.

**Comment by SeriousBuggie** [comment]
It is client related error. Render hit engine limit for render points. such happen on complicated maps which work on edge of possibilities.

Like FifthVortex. I fight with very hardly.

Since this count consists from both parts - static and from movers, and crash not immediately, It look like as make addition with time after movers appears. It can be related to used render, exact location of map and path on map, so you sse something, which increase limit count, until hot hit limit.

It must be not related to server.
