### ISSUE TITLE
Can one of the maintainers comment on Epic shutting down UT servers in January?

### ISSUE THREAD

**Issue by to-pse** [OldUnreal/UnrealTournamentPatches#1132]
https://www.gameshub.com/news/news/epic-games-unreal-tournament-rock-band-online-game-service-36719/#:~:text=%3E%20News%20%3E%20PC-,Epic%20shuts%20down%20online%20service%20for%20Unreal%20Tournament%2C%20Rock%20Band,shut%20down%20from%20January%202023.&text=Epic%20Games%20has%20announced%20several,for%20these%20titles%20being%20sunsetted.

**Comment by SeriousBuggie** [comment]
It is only about shutting down Epic master-server and remove game from stores.
This not affect actual game servers, since it is community driven, not by Epic.

If you use latest patch all be fine, since exists community master-servers, which work there before for years and continue working on.
You can check your settings here: https://ut99.org/viewtopic.php?p=139905#p139905

About stores: If you buy in Steam, then you can still reinstall game. but not able buy it from Steam if not buy it before.
You can go to GOG and buy game here. There game still in place.

**Comment by an-eternity** [comment]
It seems, soon is the time to replace Epic's master server to [OpenSpy's](http://beta.openspy.net/en/) one.
Thanks to CHC (https://github.com/chc/openspy-core-v2) and the THPSX team, this GameSpy replacement service is now working just fine.


Clients that use XBrowser begin to have problems if there is no 1 main master server that lists all existing gameservers (that currently is only the Epic's one), hope either its author or somebody else will take care of it...

**Comment by stijn-volckaert** [comment]
Right now, this is an inconvenience, but not the end of the world. There are several alternative masterservers we can use instead of Epic's utmaster. The only problem is that a lot of players and server admins will have to manually update their game/server settings to connect to the alternative masterservers instead. This includes all people who installed the 469 patches without running the exe installer. We have a [wiki article](https://www.oldunreal.com/wiki/index.php?title=Masterserver_Guide) that explains the procedure.

We're still discussing internally how we're going to deal with this in our next patch. We might update the UnrealScript code to automatically remove/replace Epic's utmaster.

**Comment by stijn-volckaert** [comment]
I put some additional info here: https://www.patreon.com/posts/unreal-25th-83522201
