### ISSUE TITLE
[469a] more than 32 bots?

### ISSUE THREAD

**Issue by gattovicentino** [OldUnreal/UnrealTournamentPatches#124]
It's obviously not an issue, since it's a limit of UT, but would it be possible to increase the maximum number of bots in the game (currently 32) in a future patch or is it impossible to modify?

**Comment by SeriousBuggie** [comment]
This is not an easy task.
The number of bots can be set only for the Practice Session.
Only the minimum number of players can be specified for the server.
As far as I understand, 32 real players is an engine limitation that cannot be changed.
In theory, you can allow in the server settings to set numbers greater than 32, so that everything greater than 32 is supplemented by bots, but the result will be so-so.

You can even now run the `addbots` command on the server or in the Practice Session to get over 32 bots.
At the same time, you will see all the problems associated with this.

In particular, the fact that only the first 32 bots are customized, because there are settings only for them.

Thus, at least there is a problem with customizing bots. It is necessary to expand the array of bot settings by adding additional elements there. Keep support for the setup of so many bots.

In any case, there will be some number. Not 32, but 64 - it doesn't matter.

32 bots are actually quite a lot. Most of the maps are not even designed for 16 bots, what to say about 32.

If you have specific maps and a specific case, you should use a mutator that will call
`Level.Game.ForceAddBot();`
The desired number of times.

I don't think there should be any changes in the current patch.

In any case, even if something is changed, the changes, even if they are simple, will be in very many places so that it looks and works fine.

**Comment by gattovicentino** [comment]
Thanks. Yes, I imagined it was difficult, due to the engine limitation. I was curious to see 64 bots together (since I have hundreds of player classes/models installed), in some specific maps, but, clearly, without the customization of each one, it wouldn't make much sense...

**Comment by stijn-volckaert** [comment]
This is technically possible, but it would break a lot of mods, so we're not going to implement this in the base game
