### ISSUE TITLE
ACE kicked for dinput8.dll

### ISSUE THREAD

**Issue by UM-Hitman** [OldUnreal/UnrealTournamentPatches#1358]
The issue is several ppl that upgraded to v469d get kicked by dinput8.dll which is a windows-file so can't be removed
[ACEv12e]: HookModule.....: dinput8.dll
[ACEv12e]: HookFunction...: DirectInput8Create

Some also rapport that the xopenGL turned way to dark after install and have to shift to D3D9

**Comment by garry-ut99** [comment]
> Some also rapport that the xopenGL turned way to dark after install and have to shift to D3D9

Yeah, here same issue reported :

> guitronimo : https://github.com/OldUnreal/UnrealTournamentPatches/issues/1356#issue-1862268726 : Its darkish

**Comment by SeriousBuggie** [comment]
This issue already addressed to ACE and will be fixed in next ACE version.
As for now, this users can goes into Input settings and choose raw input (or cursor), instead of DirectInput.
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/e20be2d6-d32f-4c2d-b278-f4734c1d0f6e)

Please use one issue, for one problem.
