### ISSUE TITLE
[469x] [Request] - Fullscreen Borderless option

### ISSUE THREAD

**Issue by esnesi** [OldUnreal/UnrealTournamentPatches#1364]
[469d] [Request] - Fullscreen Borderless option

I could not find earlier requests for this.

Request:
In case of a multiple monitor setup, it would be nice to have a "Fullscreen Borderless" option in UT99.
Not sure if this is technically possible when the window is on  "Press ESC to begin" UT-Logo-Map.unr

If more info is needed, am glad to elaborate.

**Comment by BerserkerBG** [comment]
This is a great suggestion and I have also suggested this on Discord long time ago. I have seen other people asking for this feature.

Fullscreen Borderless should be definitely doable even on all renderers. I can confirm this, because I have tested this myself by using external programs that makes UT run in Fullscreen Borderless. This method does work, but with some minor headaches. Here is a link to the program:
[WindowedBorderlessGaming.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/13061133/WindowedBorderlessGaming.zip)


You run this program and you launch UT in Windowed mode, then you press F4 to re-scale the UT window and remove the borders. Important: UT must be launched in Windowed mode, if you don't set it to run in Windowed mode trough UT.ini, then this method will not work. Here are the UT.ini changes you need to do before launching UT:
```[WinDrv.WindowsClient]
WindowedViewportX=1920
WindowedViewportY=1080
StartupFullscreen=False```

You need to do this, because for some reason, if you make your UT go Fullscreen, then toggle out of it to Windowed mode, then UT window can't be resized to 1920x1080 anymore. It is limited to 1920x1061 and you can't resize it to 1920x1080, which interferes with the WindowedBorderlessGaming program.
