### ISSUE TITLE
[468d RC2] UnrealEd: searching an event leads to AttachTag

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1394]
As subject tells: I searched for "secret" in UnrealEd in map "MH-XV-GiranTown2021v4.unr" and got the Actor MonkStatue0 that has this text in its AttachTag. Is this desired? I'd expected that result when searching for a Tag instead (but does not show up then).
```Begin Map
Begin Actor Class=MonkStatue Name=MonkStatue0
     bPushable=False
     bOnlyTriggerable=True
     Level=LevelInfo'MyLevel.LevelInfo0'
     Tag="MonkStatue"
     Base=LevelInfo'MyLevel.LevelInfo0'
     Region=(Zone=LevelInfo'MyLevel.LevelInfo0',iLeaf=-1)
     AttachTag="ELSECRETOlift"
     Location=(X=-3700.000000,Y=-8757.000000,Z=-6078.000000)
     Rotation=(Yaw=15896)
     OldLocation=(X=-3680.000000,Y=-8752.000000,Z=-6160.000000)
     bSelected=True
     DrawScale=2.000000
     CollisionRadius=44.000000
     CollisionHeight=176.000000
     Name="MonkStatue0"
End Actor
End Map
```

**Comment by SeriousBuggie** [comment]
Yes, it is intended. It is search Event in AttachTag field:
`CheckField(TEXT("AttachTag"), CharEvent) // Actor, AttachMover, MixMover`
`Event` used because this field act like `Event`, not like `Tag`.

How work `Event`? Search all match actors with same `Tag` and do something.
How work `AttachTag`? Search all match actors with same `Tag` and do something.
