### ISSUE TITLE
Rejected by servers running AnthCheckerC_v138

### ISSUE THREAD

**Issue by OMA-Bite-Me** [OldUnreal/UnrealTournamentPatches#140]
Is there a way to whitelist v469a?

![AnthCheckerC_v138](https://user-images.githubusercontent.com/59076225/97115563-bc687080-16cd-11eb-882d-018a748fccc4.png)

**Comment by stijn-volckaert** [comment]
Confirmed, but we're not going to fix this. The patch README warns for incompatibilities with CSHP and AnthChecker:

https://github.com/OldUnreal/UnrealTournamentPatches#for-server-admins

Both of these mods are outdated and have been replaced by UTPure/NewNet and ACE, respectively. AnthChecker's last update was in 2006. I've been asking admins to get rid of it since at least 2010 because ACE can do everything AnthChecker did and much much more. ACE can also automatically receive filelist updates.
