### ISSUE TITLE
[469a] unrealed ctrl select bug?

### ISSUE THREAD

**Issue by zero-khan** [OldUnreal/UnrealTournamentPatches#142]
I think that everyone has experienced this.

You hold ctrl to select multiple actors (clicking on actors one by one). Many times, when you click to select something new, it inadvertently moves everything that you have already selected.

**Comment by SeriousBuggie** [comment]
I think it is input related. Some things can happens for me in Windows Explorer too if during click mouse moved into few pixels.
Then files in explorer copied.

In UEd it happens more often from Windows Explorer, maybe because UEd use own system of input.

Maybe need add "dead zone" in few pixels when start drag with CTRL. or wait few milliseconds and if come mouse unpressed event - ignore move at all.
Little delay can be not noticeable at all.

**Comment by zero-khan** [comment]
It happens with SHIFT + click to select brushes too. Many times you click to select a brush that way, it moves the previously selected brushes.

**Comment by stijn-volckaert** [comment]
does this happen in all viewports or just in the 3d viewport?

**Comment by SeriousBuggie** [comment]
In all. Include flat.

**Comment by Chamberly** [comment]
This happen to me quite a lot, so I had to do it slower. Or the fun part is that the property menu pop up annoying the heck out of me.

**Comment by SeriousBuggie** [comment]
There can't be 100% solution, but we manage mitigate this issue for most real use cases, so it must be fine now.
