### ISSUE TITLE
[469c] 2D Shape Editor: Revolved Shape has bad Rotation Surface

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1426]
Texture alignment with Revolved Shape is bad, specifically the rotation of the surfaces. When you make an Tunnel or an Arch by using the Revolved Shape builder, you can notice in every instance where the texture surfaces are rotated in a strange angle. Here is an example of what it looks like, this is an Arch made with Revolved Shape (in 2D Shape Editor):
![Screenshot_23](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/2849d3ea-780e-4633-8b4e-19b4f11f43f1)

## Reproduce steps:
1. Download and unzip [2Dshape_Revolved_TextureAlignment.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/13168418/2Dshape_Revolved_TextureAlignment.zip)
2. Open the map 2Dshape_Revolved_TextureAlignment.unr in Ued
3. Select a Trim texture (you can select the one included in the MyLevel package)
4. Open the 2D Shape Editor and load the 2ds file (File -> Open -> RevolveArch.2ds)
5. Place and Add this brush in the map by using the Revolved Shape button with these values (screenshot):
![Revolve Settings](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/f61cc0fd-7eeb-4148-948b-74e07418beb9)

## Result:
![Screenshot_22](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/cfdc7040-53af-478d-824e-7ad53dfc83fa)

![Screenshot_21](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/9d64d484-16a7-4a0f-a3ae-72fe246d5ca7)

## Current workaround:
You will have to manually fix the correct rotation of the surfaces by either eyeballing it with the Texture Rotation tool, or by using math with custom rotation. In this specific example with the Arch is rather easy to solve, you divide 45/4 and you get 11.25 which can be used to fix the rotation. Here is what it looks like:

https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/3bc51a2b-8cce-46cb-8dd0-8ce8228a57c2

This is a best scenario example and its very easy to solve, however, if the 2D Shape Brush has more complicated detail, like bevels or more geometry, it can be rather difficult and incredibly time consuming to find the perfect rotation for the surfaces. This is why I'm hoping someone to come up with a solution for this by fixing the texture rotation when placing a Revolved Shape brush.

**Comment by SeriousBuggie** [comment]
It is because 2d editor not really care about texture align at all :)
So it just make it. And all goes unaligned. I guess it can be tuned.
And for other actions possible too need do it properly.

**Comment by SeriousBuggie** [comment]
It goes be like that:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/cbfb6e55-1db1-41a0-a6fb-c72d7a4b250e)
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/abe5572f-6b0b-4196-881f-5464b440d1a9)
But this not exactly what you mean:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/0f775143-a7be-42bb-9864-c07a119d4e01)
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/73778e41-6f30-4217-9b5a-6ff8ed8fd768)

Since there no really way easy determine which side left and which is right (base shape can be any form, not exactly cube), then one side goes be upside down.
But this can be easy altered by rotate on 180 if need. it is easy operation. no need any hard math.

There example not cube base:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/79c915cb-e082-45f4-a5d7-1d8059a8e722)
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/d3ba2399-ad19-4eb0-b66d-21e02a7ab43a)
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/74d3b496-9f1e-4602-bdf7-a52ec71d046c)
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/dd4f8b38-0027-4290-8794-a2668a413fc4)
