### ISSUE TITLE
[469d] One Tile alignment ruined after map rebuild

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1543]
One Tile align has a bug when you rebuild a map - it will ruin the alignment when you rebuild a map.

Example of an aligned surface with one tile:
![Screenshot_147](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/83dc81c2-bc10-4825-812f-9f6937f04472)

This is what happens after I rebuild the map, notice the texture alignment has been offset:
![Screenshot_148](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/63d41c1d-f6c8-4cbb-b64d-d771f975dbab)

Reproduce:
1. Open OneTileBug1.unr in Ued. [OneTileBug1.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/14512395/OneTileBug1.zip)
2. Look at the aligned surface, which is referenced in the screenshots above.
3. Rebuild the map.

Expected result:
Surface alignment stays in place.

Actual result:
Surface alignment got offset when we rebuild the map.

**Comment by SeriousBarbie** [comment]
Have you build it from scratch or taken the bar from another map (or elsewhere)? Also it looks like the brush has been scaled.

**Comment by SeriousBuggie** [comment]
This happen because OneTile modify Origin of texture. Which reset on map rebuild.
OneTile can use Pan in some sort, for do same look, however on attempt rotate texture it will goes not as for now.
So I guess better preserve Origin on rebuild map.

**Comment by SeriousBuggie** [comment]
Well, it is not good formed align. U V not in plane.
You can unalign texture, rotate on 90 degree, apply one tile, and it will be fine for rebuild.

Reason next: since UV not in plane it produce Origin outside plane too. Which "land" to plane during build.
However, since UV not orthogonal to Normal such land change texture align.
Normally UV must be orthogonal to Normal in this case fix Origin via Land not change visual align.

I suspect such brush be crafted by vertex edit. So Normal changed, but UV - no.

I will look what can be done for OneTile handle such case and produce Origin in plane.
This will fix exactly this problem, however UV not in plane can cause other problems, so better avoid it.

**Comment by SeriousBuggie** [comment]
Fix this issues mean not fix build, nothing wrong with build here. it mean fix one tile align. So you need in all such cases apply one tile align again for make it proper.
