### ISSUE TITLE
[469d] Disappearing movers polys when count mover vertices is more from count of vertices for static BSP

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1597]
Movers can disappear if they are overlapping with certain bsp cuts.

Here is an example video, notice how some of the movers disappear when they reach Key2:

https://github.com/user-attachments/assets/0f1f5a32-ad17-4360-95f6-c02b2b20050e

# Reproduce:
1. Play this map in UT [DisappearingMovers.zip](https://github.com/user-attachments/files/16321576/DisappearingMovers.zip)
2. Touch the trigger to activate all movers

# Explanation:
My observation about this issue is that it happens because some of the movers edges are *touching* certain bsp cuts, meaning both the mover surface and bsp cut are overlapping on a certain plane (X Y or Z). I found out if I move the movers slightly (even by 1 unit), the movers surface is no longer aligned with the bsp cuts and as a result the movers are no longer disappearing.

Lets compare this with the video example I showed above. Here is how it looks like in the 2D viewport:
![image](https://github.com/user-attachments/assets/6da1aa08-bc5a-492f-8751-684f52a52960)
The movers in this screenshot are currently at Key2. The yellow line below represents the subtracted brush of the room, in this case the yellow line is the floor. I want you to pay attention how the floor surface is overlapping with the mover edge on the Z plane. I discovered that if I move the Key2 position of the mover it actually fixes this problem, because the bottom edge of the mover is no longer overlapping with the floor surface. It looks like this:
![image](https://github.com/user-attachments/assets/718815cb-c4f4-43c4-a466-7c597b3d9fb1)

This screenshot results in movers that are not disappearing like the video. And this is because I've offset the Key2 position of the movers so they don't overlap with the floor.

**Comment by SeriousBarbie** [comment]
Nice tip to avoid invisible getting movers, thanks.
There have been always problems with that (see UT99.org-[Disappearing movers](https://ut99.org/ut99.org/viewtopic.php?p=94521) for example).

**Comment by SeriousBuggie** [comment]
Test case not relevant to your description.
> Movers can disappear if they are overlapping with certain bsp cuts.

Here movers disappear because not enough vertices polls for display it.
It rare artificial case.

Here map which prove it:
[DisappearingMovers2.zip](https://github.com/user-attachments/files/16487403/DisappearingMovers2.zip)

All 45 movers move below ground.
And keypos 1 increased, so they not touch floor, at end of movement.

However they still disappear.

Reason is simple - there 45 movers. And one cube in static BSP.

Each mover consume 24 items for vertices. 6 sides with 4 vertices. 1080 items total.
Static BSP consume 24 items.

Mover Tracker allocate 24 + 512 items. Which not enough for display all movers.

We will fix that. but this issue not relevant what you try make test case for.
And exactly this issue can happen only when count of vertices on mover bigger from count of vertices on static BSP.
Which is super rare.
Also it is not general count, but actual count. So it can be less from real count vertices per brush (for every poly).
Since usually not all vertices of mover really visible.

**Comment by SeriousBuggie** [comment]
> This screenshot results in movers that are not disappearing like the video. And this is because I've offset the Key2 position of the movers so they don't overlap with the floor.

On your second case, mover surfaces below floor, so not need vertices. So vertices enough for render all.
