### ISSUE TITLE
[469a] Crosshair misaligned

### ISSUE THREAD

**Issue by prom6** [OldUnreal/UnrealTournamentPatches#16]
The Crosshair is misaligned  on weapon model shown left/right. On center or weapon model hidden its aligned correctly.
Ok I guess its already in the old patch, never noticed it like that.

**Comment by stijn-volckaert** [comment]
Confirmed. However, this misalignment was an intentional design decision. If you carry your weapon in the left or right hand then the shots or projectiles your weapon fires do not originate from your player's position, but rather from the position where the weapon is rendered. You can also see this if you fire a close-range enforcer shot. The bullet decal will be slightly off-center, just like the crosshair.

Making the crosshair reflect where the shot is actually going to "land" requires a fair bit of math and some UScript modifications. We intend to work on this, but it might take a while.

**Comment by stijn-volckaert** [comment]
We added an option for crosshair alignment in 469b. You can enable it in the options>preferences>HUD menu. Note that some servers run older mods that may override the updated behavior, so YMMV.
