### ISSUE TITLE
Humble Requests for Upcoming Patch

### ISSUE THREAD

**Issue by dov910** [OldUnreal/UnrealTournamentPatches#1600]
Hi Antrax,

I hope this message finds you well. I have two humble requests for the upcoming patch:
```

1) Increase Actor Channels Limit: I kindly request an increase in the actor channels limit to either 2,048 or 4,096, or alternatively, the option to set this limit manually.

2) Multi-CPU Core Utilization: Could you please add support for multi-CPU core utilization in the Linux ARM64 and standard Linux patches? I trust that the Windows patch is functioning as expected.

```
Thank you for considering these requests. I look forward to your response.

Regards,
Deepu

**Comment by an-eternity** [comment]
I would like to join this request too and already thought about it a while ago, but... Item 1 means it is a server with broken network backward compatibility; and item 2 (if that is not just about sound/graphics drivers run in a dedicated threads, but main thread with its sequential tasks chain split into a several threads) is too complicated (practically undoable) work...

**Comment by dov910** [comment]
Okay, then ignore the first request and can you consider the 2nd one?

Why does a dedicated UT server on Windows utilize all CPU cores, while this isn't working with Linux? You're right that a dedicated server doesn’t need graphics or sound, but if we have more monsters and players on the server, the first core always suffers, staying at 100% CPU usage while the total core usage is 25%. Is there any possible way to fix this issue with LinuxARM64 but platform?

**Comment by an-eternity** [comment]
I thought about this problem... And i don't think it is practically possible to redesign an entire engine for parallel tasks execution.

What i think is probably possible - is to implement a native mutator extensions that would provide an opportunity to unload some amount of tasks (specifically, that kind of tasks which doesn't need any hard synchronization) to an external thread that would execute that special native mutator asynchronous code. This way we could free main server thread (in some amount) in order to increase its potential capability to support more players, bots and other CPU-demanding game-type specific things...

I have been considering to make a suggestion for such kind of native mutator extension, but i have a number of doubts... Which in the end follow to this question - is it worth to do it at all? (I still don't know an answer)
For the time being we implement _a way of optimization_ in order to fix both (1 and 2) issues, but of course we hit the limits where optimization is no longer possible... So, it would be nice if some native part advantages in the future patches would give us more of opportunities...

Well, anyway, let's wait for dev's official answer...

**Comment by an-eternity** [comment]
> Why does a dedicated UT server on Windows utilize all CPU cores, while this isn't working with Linux?
In Windows it is still only the one main thread, its execution is distributed among all cores, and also an additional threads that run graphics driver, some secondary tasks and etc.... It is not a full multicore support actually.

**Comment by dov910** [comment]
Yes, you're right. I'll look into the `AlwaysRelevant=True` objects, which are set by default for the begin state of inventory items and other classes.

**Comment by dov910** [comment]
> > Why does a dedicated UT server on Windows utilize all CPU cores, while this isn't working with Linux?
> 
> In Windows it is still only the one main thread, its execution is distributed among all cores, and also an additional threads that run graphics driver, some secondary tasks and etc.... It is not a full multicore support actually.

![image](https://github.com/user-attachments/assets/17b1c486-0c87-4c53-b47d-b1e93ac028e9)

**Comment by dov910** [comment]
Okay guys thanks for the reply, the first channel eating issue I was shorted out.

**Comment by an-eternity** [comment]
Two or more cores can't run one the same thread in the same time.
Thread is being automatically switched to a less loaded core, according to affinity settings.
Depending on specific hardware (mostly old CPU's and VM's) single core affinity setting may result in even better performance, comparing to all cores affinity setting.

**Comment by dov910** [comment]
I'm using Linux on an ARM64-bit system, which has automatically allocated CPU affinity to 4 cores. Unfortunately, the `UCC.bin` process is fully dependent on core 1. When `UCC.bin` reaches 100% usage, it doesn't distribute the load to other cores. As a result, I see 25% usage across the total cores, with 100% on the main core. IDK anyway I can adjust with core 1.
