### ISSUE TITLE
HD Skins 3.1 General Protection Fault with DX11

### ISSUE THREAD

**Issue by HighValueWarrior** [OldUnreal/UnrealTournamentPatches#1711]
Using HD Skins 3.1 https://www.moddb.com/mods/high-resolution-unreal-skins/downloads/unrealhd-v30-full with DX11 renderer results in General Protection Fault.

**Comment by metallicafan212** [comment]
Which directx 11 render?

**Comment by HighValueWarrior** [comment]
The first one in the list for recommended renderers D3D11.
Not ICBIND (D3D11),

**Comment by metallicafan212** [comment]
After it crashes, can you upload UnrealTournament.log here?

**Comment by HighValueWarrior** [comment]
Here you go. 
Merry Christmas - thanks for all you do for UT
[UnrealTournament.log](https://github.com/user-attachments/files/18242735/UnrealTournament.log)

**Comment by metallicafan212** [comment]
Thanks, I'll get it looked at. Looks like it's crashing when loading one of the textures.

**Comment by HighValueWarrior** [comment]
Just fyi, this is on a brand new install. 
I used the full installerl here https://www.oldunreal.com/downloads/unrealtournament/full-game-installers/ 
- then added bonus pack 4  + bonus pack 4 fix. 
- then I installed HDskins and the 4k textures.
I have tried fresh installs several times and same result.

**Comment by metallicafan212** [comment]
Which 4k texture pack did you install?

**Comment by HighValueWarrior** [comment]
4k textures  
https://www.moddb.com/mods/ut99hd/downloads/unreal-tournament-hd-texture-pack-30

I did some more testing on clean installs and the issue is in the 3.1 HD skin mod. 
There are two mutators, one for the armor which work  .....s and the HD skins mutator which causes the protection fault when enabled. I hope that helps.

**Comment by Annonymous5542** [comment]
Having the same issue. I use HD skins 3.1 since it fixed a lot of the weapon model issues (and HD skins of course). 

![image](https://github.com/user-attachments/assets/4c56e06c-c48a-4930-a383-5d52c064c194)

**Comment by SeriousBuggie** [comment]
Memory ended. 32-bit game can't handle more then 2-3 GB of RAM. So if you use huge textures, memory can ended and game crashes in random place where want allocate memory.

**Comment by HighValueWarrior** [comment]
I have used these skins and textures before without issue.
It crashes with only HDskins installed - that mutator is 1.4 gb well under 3 gigs.

**Comment by Annonymous5542** [comment]
I had used this before without any issues on 469c. I did use it in collaboration with XC_engine, dunno if that played a factor. Just today I had installed 469e.

**Comment by SeriousBuggie** [comment]
I use HD skins with d3d11 long-long time on 469e. it is fine for me. However, I not use weapons mutator.
And real memory footprint depends from used mods and maps.
In my case no such crashes.
However in your case they can bee, if you use mods and/or maps, which need load more HD textures.

**Comment by HighValueWarrior** [comment]
Same experience as Annoymous. Was fine before. 
Anyway, reported and corrorated. 
I will leave it to you coders to figure out.

**Comment by metallicafan212** [comment]
PC GPUs don't just load a texture once, they keep a copy in system memory and a copy in video memory.

In the worse case, you're looking at double the ram usage than the size, 1.4 * 2 = 2.8gb, leaving the game to run with just 200mb of ram in this scenario for everything other than just textures. 469e uses a bit more ram than 469d so I'm not surprised if 4k textures in a 32bit app suddenly started crashing.

Back when skyrim was new, I used texture mods, and had to customly compress them to make sure the game didn't crash since normal skyrim is a 32bit app.

Try getting a reduced size if it's available. 4k textures are absolutely massive, they're larger than a 4k screen. 2048 (2k) is massive even now, for texture.

**Comment by Annonymous5542** [comment]
If you mean to use HD skins as in: replacing the .utx files in the texture folder, then yes, I never have issues with that. All versions of 469 ran that perfectly fine.

HD 3.1 mutator updates the weapon, player model and item skins, and also fixed wonky weapon model positions.

**Comment by HighValueWarrior** [comment]
I just tried with D3D9 crash and opengl it worked for a bit, then frames slow way down after a few mins.
Guess that is it for the old girl. 
I may try the next patch if it works with the HD textures again as before.
Happy fragging gents.

**Comment by SilverDash** [comment]
It was never supposed to work. 32-bit means it will crash no matter what. If we move to 64-bit that means bye bye Windows XP and Network-Compatibility.

D3d9 will always crash, OpenGL is running slow because it's using a max of 4 gigs. The game will never be able to use more.
DX11 will crash because it tries to use more than the allowed ram. If it didn't, it will slow the game down. 

This will not be fixed anytime soon unless a 64-bit UT99 patch is released. That will break Network-Compatibility and won't happen in 469 ever.
