### ISSUE TITLE
[469a] Wrong Skin/Missing Model for Trophy Room as Skaarj Hybrid.

### ISSUE THREAD

**Issue by Xanious** [OldUnreal/UnrealTournamentPatches#189]
Successfully completing one of the gametypes in the campaign as a skaarj hybrid results in a male commando with the skaarj hybrid texture misplaced instead of the proper model and animations 
![Shot00005](https://user-images.githubusercontent.com/77414568/104510831-c6f22200-55b9-11eb-835c-ede6ad33d8b7.png)

**Comment by stijn-volckaert** [comment]
do you see any errors in UnrealTournament.log when this happens?

**Comment by SeriousBuggie** [comment]
Reproduce:
1. Start UT.
2. Setup player as:
![scr_1616545450](https://user-images.githubusercontent.com/70026933/112235794-0a1ae200-8c48-11eb-9e71-965fc41d4eec.png)
3. Run in console: `open EOL_Deathmatch.unr?Game=Botpack.TrophyGame`

In log nothing unusual:
```
ScriptLog: Team 0
ScriptLog: Login: Buggie
ScriptLog: set multiskin TSkMSkins.Warr Dominator
ScriptLog: Warr Dominator  TSkMSkins.
ScriptLog: set multiskin tskmskins.PitF tskmskins.Baetal
ScriptLog: PitF Baetal tskmskins. tskmskins.
Log: Possessed PlayerPawn: TSkaarj EOL_Deathmatch.TSkaarj0
Init: Initialized moving brush tracker for Level EOL_Deathmatch.MyLevel
DevMusic: ALAudio: Transiting to Music Ending.Ending, SongSection 0 with MTRAN 3
DevMusic: RegisterMusic Music Ending.Ending
Log: ALAudio: playing Ending  (Impulse Tracker 2.14v5 IT 1.00)
```

**Comment by SeriousBuggie** [comment]
For render final Mesh use next code:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/TrophyGame.uc#L21
```
	foreach AllActors(class'TrophyDude', TD)
	{
		TD.Mesh = Mesh(DynamicLoadObject(SpawnClass.Default.SpecialMesh, class'Mesh'));
		TD.Skin = NewPlayer.Skin;
		for (i=0; i<8; i++)
			TD.MultiSkins[i] = NewPlayer.MultiSkins[i];
	}
```
`SpawnClass.Default.SpecialMesh` set (for example) as:
[Botpack/TMale2.uc](https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/TMale2.uc#L115): SpecialMesh="Botpack.TrophyMale2"

Full list you can see at https://github.com/Slipyx/UT99/search?q=SpecialMesh

Each mesh must contains two animation, according to:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/TrophyDude.uc
`Trophy4` and `Trophy5`.

If no SpecialMesh specified - use default mesh:
`Mesh=LodMesh'Botpack.TrophyMale1'`
And player skin on it.

MultiMesh/Classes/TSkaarj.uc not set SpecialMesh because EpicCustomModels.u (which contains Nali, WarCow, and Skaarj meshes) do not contain such animations.

**Comment by SeriousBuggie** [comment]
Oh. Things is more complicated.
![scr_1616547752](https://user-images.githubusercontent.com/70026933/112238467-63d1db00-8c4d-11eb-9856-1911f4b532d5.png)
customplayer.uc:
```
defaultproperties
{
	PlayerReplicationInfoClass='MultiMesh.CustomPlayerReplicationInfo'
	Handedness=-1.000000
	FallBackMesh=Mesh'Botpack.Commando'
	Mesh=Mesh'Botpack.Commando'
	SelectionMesh="Botpack.SelectionMale1"
	SpecialMesh="Botpack.TrophyMale1"
	JumpSound=TMJump3
	LandGrunt=MLand3
	CarcassType=TMale1Carcass
	Menuname="Custom Player"
	VoiceType="BotPack.VoiceMaleOne"
	TeamSkin1=2
	TeamSkin2=3
	FixedSkin=0
	FaceSkin=1
	DefaultSkinName="CommandoSkins.cmdo"
	DefaultPackage="CommandoSkins."
}
```
So `SpecialMesh="Botpack.TrophyMale1"` for Nali, Cow, Skaarj.

**Comment by SeriousBuggie** [comment]
If try use Mesh instead of SpecialMesh it is look not good:
![scr_1616548086](https://user-images.githubusercontent.com/70026933/112238966-536e3000-8c4e-11eb-9f77-6c75eeb6ee5d.png)

Also produce log message:
`Log: TrophyDude EOL_Deathmatch.TrophyDude0 (Function Botpack.TrophyDude.Timer:0016) PlayAnim: Sequence 'Trophy5' not found in Mesh 'TSkM'`

**Comment by SeriousBuggie** [comment]
Best solution: https://streamable.com/i00uwc

 Changes in code:
```
class TrophyDude extends Decoration;

var bool bFinal;
var int Pos;

function PostBeginPlay()
{
	SetTimer(38.0, True);
}

function Timer()
{
	SetTimer(0.0, False);
	if (HasAnim('Trophy5'))
		PlayAnim('Trophy5', 0.3);
	else 
		if (HasAnim('Victory1')) 
			PlayAnim('Victory1', 0.5);
	Pos = 0;
}

function AnimEnd()
{
	if (Pos < 2)
	{
		if (HasAnim('Trophy4')) 
		{
			PlayAnim('Trophy4', 0.3);
			Pos++;
		}
		else 
			if (Pos == 0 && HasAnim('Taunt1')) 
				PlayAnim('Taunt1', 0.4);
			else
				if (HasAnim('Breath1')) 
					PlayAnim('Breath1', 0.3);
		Pos++;
	}
}
```
```
class TrophyGame extends UTIntro;

var Class<Trophy> NewTrophyClass;
var int TrophyTime;
var rotator CorrectRotation;
var LadderInventory LadderObj;
var bool bTrophyInit;

event PlayerPawn Login
(
	string Portal,
	string Options,
	out string Error,
	class<PlayerPawn> SpawnClass
)
{
	local PlayerPawn NewPlayer;
	local TrophyDude TD;
	local int i;
	local Mesh M;

	NewPlayer = Super.Login(Portal, Options, Error, SpawnClass);

	if (SpawnClass.Default.SpecialMesh == "" || 
		(SpawnClass.Default.SpecialMesh == "Botpack.TrophyMale1" && SpawnClass.Default.Mesh != LodMesh'Botpack.Commando') ||
		(SpawnClass.Default.SpecialMesh == "Botpack.TrophyMale2" && SpawnClass.Default.Mesh != LodMesh'Botpack.Soldier') ||
		(SpawnClass.Default.SpecialMesh == "Botpack.TrophyFemale1" && SpawnClass.Default.Mesh != LodMesh'Botpack.FCommando') ||
		(SpawnClass.Default.SpecialMesh == "Botpack.TrophyFemale2" && SpawnClass.Default.Mesh != LodMesh'Botpack.SGirl'))
	{
		M = SpawnClass.Default.Mesh;
	}
	else
	{
		M = Mesh(DynamicLoadObject(SpawnClass.Default.SpecialMesh, class'Mesh'));
	}	

	foreach AllActors(class'TrophyDude', TD)
	{
		TD.Mesh = M;
		TD.Skin = NewPlayer.Skin;
		for (i=0; i<8; i++)
			TD.MultiSkins[i] = NewPlayer.MultiSkins[i];
		if (TD.HasAnim('Wave'))
			TD.PlayAnim('Wave', 0.3);
	}

	return NewPlayer;
}
```
Previous class still play same. Custom models fine too. Finally I little speed up latest taunt. In video 0.3 speed in code 0.4.
