### ISSUE TITLE
[469b] Set placeholder BugAddress to github link

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#232]
I suggest after code:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/UTServerAdmin/UTServerAdmin.uc#L404
```
	//Response.Subst("BugAddress", "utbugs"$Level.EngineVersion$"@epicgames.com");
    //Response.Subst("BugAddress", "utpg@utpg.org");
```
add 
```
Response.Subst("BugAddress", "https://github.com/OldUnreal/UnrealTournamentPatches/issues");
```
For replace placeholder `BugAddress` to github link

**Comment by stijn-volckaert** [comment]
This is not really necessary since we replaced:
```
<td width="1" align="RIGHT" valign=middle><font face="Verdana,Arial" size="-1" color=white><b>«</b><a href="mailto:%BugAddress%">Bugs?</a><b>»</b></font></td>
```

by:
```
<td width="1" align="RIGHT" valign=middle><font face="Verdana,Arial" size="-1" color=white><b>«</b><a href="https://www.oldunreal.com">Bugs?</a><b>»</b></font></td>
```

in the webadmin source code. As for linking directly to GitHub: right now, this makes sense, but we don't know if GitHub is going to stick with this URL layout. It is probably safer to link directly to the oldunreal web page and to add a bug report link there.
