### ISSUE TITLE
[469b] Skin FCommandoSkins_Negaverse_Titus show face in drop down twice

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#252]
Reproduce:
1. Select [FCommandoSkins_Negaverse_Titus](https://github.com/OldUnreal/UnrealTournamentPatches/files/6175169/FCommandoSkins_Negaverse_Titus.zip) and try select face

Expected result: (from v436)
![scr_1616231789](https://user-images.githubusercontent.com/70026933/111865110-c2f1d000-896d-11eb-83ba-a8d8c250446d.png)
Actual result: (from v469b)
![scr_1616231853](https://user-images.githubusercontent.com/70026933/111865128-e452bc00-896d-11eb-89f3-1d53da996535.png)

**Comment by OjitroC** [comment]
Works OK for me - no duplicate face - probably you get that because you have the Negaverse_Titus_fix skin installed as well? If so take the .init and .utx files out and try again.

**Comment by SeriousBuggie** [comment]
Yep, you right. In my System dir present another int file `FCommandoSkins_Negaverse_Titus_fix.int`:
```
[public]
Object=(Name=FCommandoSkins_Negaverse_Titus_fix.ttus1,Class=Texture,Description=Negaverse_Titus_fix)
Object=(Name=FCommandoSkins_Negaverse_Titus_fix.ttus1t_0,Class=Texture)
Object=(Name=FCommandoSkins_Negaverse_Titus_fix.ttus1t_1,Class=Texture)
Object=(Name=FCommandoSkins_Negaverse_Titus_fix.ttus1t_2,Class=Texture)
Object=(Name=FCommandoSkins_Negaverse_Titus_fix.ttus1t_3,Class=Texture)
Object=(Name=FCommandoSkins_Negaverse_Titus_fix.ttus2,Class=Texture)
Object=(Name=FCommandoSkins_Negaverse_Titus_fix.ttus4Titus,Class=Texture,Description=Titus)
Object=(Name=FCommandoSkins_Negaverse_Titus_fix.ttus5Titus,Class=Texture)
```
But in any case why this produce duplicate? This look like error, because must be only one item, named as specified in INT file.
Or package does not matter? Must be unique name of textures inside it?

**Comment by OjitroC** [comment]
Yes, the package doesn't matter and yes there must unique names for the textures (names after the filename.).  So you get two faces because Negaverse_Titus and Negaverse_Titus_Fix both have ttus4Titus for the Face - the 'Engine' reads the Face from both ints and as the face texture names (ttus4Titus) are the same it gves you two faces for Negaverse_TItus. So not an error.

I've tested this locally having both Negaverse_Titus ints/utx files and then taking the N_T_Fix files out and can confirm that with both sets of files in their folders I get two faces and with just the N_T files I get only one Face. 

I also have experience of this with two different Female Commando skins - different file (int/utx) names - same name for the face (the part after the filename.) - the face from one shows up in the other in the Player selection window even though not in that skin's int or utx.

**Comment by SeriousBuggie** [comment]
OK, then. Look like this not a issue. So I close it now.
