### ISSUE TITLE
[469b] Taunts are not audible after typing in the chat

### ISSUE THREAD

**Issue by dizzy-egg** [OldUnreal/UnrealTournamentPatches#278]
Noticed this bug since the official release of 469b. 
Online and offline, with multiple audio codecs.

Performing a voice taunt straight after typing a chat message results in the taunt being muted / not playing.

Performing multiple taunts in a row seems unaffected.

**Comment by SeriousBuggie** [comment]
Can confirm. On v436 fine. On v469b - bugged.

Possible because
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/ChallengeVoicePack.uc#L345
`&& (Level.TimeSeconds - PlayerPawn(Owner).LastPlaySound > 2)  ) `
So sounds from your message update `PlayerPawn(Owner).LastPlaySound` and voice message for next 2 seconds is muted.

IDK, this can be intended change.

Look at this comment:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Engine/PlayerPawn.uc#L1533
`LastPlaySound = Level.TimeSeconds;	// so voice messages won't overlap`

**Comment by SeriousBuggie** [comment]
`simulated function PlayBeepSound()`:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/TournamentPlayer.uc#L647
v436:
```
	PlaySound(sound'NewBeep',SLOT_Interface, 2.0);
```
v469a:
```
	PlaySound(sound'NewBeep', SLOT_Interface, 2.0, true);
```
v469b:
```
	ClientPlaySound(sound'NewBeep', true);
```

Look like unintended change when try mess with that (big text in comment):
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/TournamentPlayer.uc#L133

**Comment by unrealtitle99** [comment]
Just to add that this issue remains in 469c-RC3.

**Comment by stijn-volckaert** [comment]
Fix pushed for the 469c release version
