### ISSUE TITLE
[469b] LevelInfo.ComputerName is set to a Group name

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#286]
I noticed that sometimes _LevelInfo.ComputerName_ is set to a Group name:
```
Begin Map
Begin Actor Class=LevelInfo Name=LevelInfo0
     TimeSeconds=531.518494
     Summary=LevelSummary'MyLevel.LevelSummary'
     VisibleGroups="Group1,Test,None"
     ComputerName="Group1"
     AIProfile(0)=111051
     Level=LevelInfo'MyLevel.LevelInfo0'
     Tag="LevelInfo"
     Region=(Zone=LevelInfo'MyLevel.LevelInfo0',iLeaf=-1)
     Name="LevelInfo0"
End Actor
...
```
Unfortunately I cannot give steps to reproduce. I encountered it when messing around with [this issue](https://github.com/OldUnreal/UnrealTournamentPatches/issues/285).

**Comment by SeriousBuggie** [comment]
In `LevelInfo.ComputerName` stored comma-separated list of groups with enabled padlock.
So reproduce steps is easy:
1. Add actors to group.
2. Press padlock button near group name.

Now if you export entire map you see `ComputerName` filled with comma-separated list of groups with enabled padlock.

**Comment by stijn-volckaert** [comment]
Confirmed. However, this was very much done by design. We needed some property to store locked groups in. 227 introduced a new LevelInfo variable for this. In 469, we opted to reuse an existing variable because a lot of native mods rely on the layout of the Core, Engine.Actor, and Engine.LevelInfo classes not changing. If this decision turns out to have unintended side-effects, then it is very much open to reevaluation.
