### ISSUE TITLE
[469b] Render file mismatch

### ISSUE THREAD

**Issue by OMA-Bite-Me** [OldUnreal/UnrealTournamentPatches#293]
Hi,
While joining a particular map, "FNLittleSoldiersV[OMA]", some people are getting a file mismatch.  It just says "Render" with no file extension.   

![image0](https://user-images.githubusercontent.com/59076225/113239652-2981c280-9279-11eb-9239-87f7e217c580.jpg)

Windows 10 machines running 469b patch and D3D9.

Thanks

**Comment by an-eternity** [comment]
It is old issue, usually happens (with maps that import textures from "Render.utx" file) if there is file "Render.u" located in the "System" directory.

**Comment by OMA-Bite-Me** [comment]
it's weird that some people get this issue, but some do not.  Me and one of
my friends have virtually the same UT setup, he has issues, but I do not.

So if he deletes render.u the problem should go away?

**Comment by TankBeef** [comment]
Have you tested with OpenGL?

**Comment by OMA-Bite-Me** [comment]
No i haven't.  D3d9 works so much better for me do i don't consider opengl
normally

**Comment by TankBeef** [comment]
I am asking because someone had the same issue with another map (DM-DarkMind), and switching to OpenGL solved it. I will test the Little Soldiers map in a while with both renderers.

**Comment by an-eternity** [comment]
> it's weird that some people get this issue, but some do not. Me and one of my friends have virtually the same UT setup, he has issues, but I do not. So if he deletes render.u the problem should go away?

In all the cases i know, removing this file at the server and the client sides fixed this problem.
In some cases, renaming the file from "Render.u" to "render.u" helps, but then problem happens with another maps anyway. Because when objects are being imported from the files, file extension is not taken into account.
In this case, if Render.utx appears in the list prior to Render.u - problem does not happen, if otherwise then it happens.

One of the common example of this problem: some maps that could be downloaded from the sites (such as ut-files, UnrealArchive, etc.) contain the files "UnrealShare.uax" and "Engine.uax" located in the "Sounds" directory, which actually are a renamed UnrealShare.u and Engine.u files (taken either from v432 or v436). When admins install such maps on their servers, package name conflict related problems begin to occur...

**Comment by stijn-volckaert** [comment]
You can probably solve this by deleting the Render.u file from your system folder. It's a dummy file that happens to mismatch with a texture file some maps are using.

**Comment by stijn-volckaert** [comment]
Render.u is no longer part of the patch. People that still run into this problem can fix it by deleting Render.u from their UT/System folder
