### ISSUE TITLE
[469b] Network paths not work in some cases

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#300]
Reproduce:
1. Start [SP-Vale_1.1.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6283248/SP-Vale_1.1.zip)
2. When you on start bridge:
![scr_1617944284](https://user-images.githubusercontent.com/70026933/114130499-5f721700-9909-11eb-8962-d31bbc6fd381.png)
run in console `showall`, `showlog` and `rememberspot`
3. Walk slightly forward:
![scr_1617944402](https://user-images.githubusercontent.com/70026933/114130629-a5c77600-9909-11eb-91c8-9a8617c7ed1f.png)
run in console `showpath`

Expected result: in log appear `ScriptLog: found path` and you see Lantern on closest PathNode.
Actual result: in log appear `ScriptLog: didn't find path` and no any Lantern on closest PathNode.

UnrealEd show paths here:
![scr_1617944610](https://user-images.githubusercontent.com/70026933/114130863-24241800-990a-11eb-94b6-be872028a143.png)
But in fact only path after PathNode553 work.
Path before PathNode555 not work at all.

v436: bugged.
v469b: bugged.

**Comment by an-eternity** [comment]
I noticed long ago that for some reason "FindPathTo" and "FindPathToward" don't work properly in some cases, even if there are no any obstacles between Actors and even if "ActorReachable" returns True, these functions return None anyway. For this reason we had to rewrite the scripts so that only not-None results of these functions are taken as reliable results, and the None results are ignored.

**Comment by SeriousBuggie** [comment]
Duplicate of #389
