### ISSUE TITLE
[469b] pasted text is invisible in UnrealEd's code window

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#353]
If complete text in the code window is removed, inserted text from the clipboard or keyboard is invisible.
Steps to reproduce:
1) Open code editor.
2) If there is existing text, remove it.
3) Type text from keyboard or insert text from clipboard.
Result: text is invisible (select it to see it)
Result in v436: text is visible.

**Comment by SeriousBuggie** [comment]
Text is not an invisible. Text is black on blue background.
Because you paste plain text in [RTF editor](https://en.wikipedia.org/wiki/Rich_Text_Format). So applied default text color, because there no RTF tags.
It is black. Obviously it must be not black if background is blue.

Also if you paste plain text not in empty editor, pasted text give color of nearest text.

As possible fix:
1. Make default color not black.
2. On paste text call recolor text routine, like double click on file name do.

**Comment by SeriousBarbie** [comment]
Oh, maybe my monitor does not distinguish much between black and dark blue. Thanks for enlightenment.

**Comment by stijn-volckaert** [comment]
I can confirm that the text is black when you type. Copy pasted text turns up green for me, however.

**Comment by SeriousBuggie** [comment]
Green text usually mean comment. Possible you not clear content fully.
Reproduce:
1. Select all text of any class.
2. Cut to clipboard.
3. Paste text to notepad.
4. Select all text in notepad.
5. Cut to clipboard.
6. Paste into UnrealEd.

**Comment by Chamberly** [comment]
I just copy and pasted this text and it turns out to be the green/commented texts. Grabbed it from [ut99.org](https://ut99.org/viewtopic.php?p=128660#p128660).

![image](https://user-images.githubusercontent.com/11419314/117004093-ac9c9b00-acb3-11eb-9792-575b689855f2.png)

**Comment by SeriousBuggie** [comment]
Delete all text before paste.

**Comment by Chamberly** [comment]
> Delete all text before paste. And copy from notepad, not from browser, because it able convert HTML to RTF.

I still have the green text, copy and pasted from Notepad++ and the old notepad.

**Comment by SeriousBuggie** [comment]
`Ctrl+A`, `Delete`, `Ctrl+V`?
