### ISSUE TITLE
[469b] Mover not able kill any Pawn except PlayerPawn

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#410]
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Engine/Mover.uc#L624
```
	else if( MoverEncroachType == ME_CrushWhenEncroach )
	{
		// Kill it.
		Other.KilledBy( Instigator );
		return false;
	}
```
But 
`event KilledBy( pawn EventInstigator );` from `Actor` implemented only in `PlayerPawn` as
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Engine/PlayerPawn.uc#L3727
```
function KilledBy( pawn EventInstigator )
{
	Health = 0;
	Died( EventInstigator, 'Suicided', Location );
}
```
So suggested implement this in same way in `Pawn`.

**Comment by an-eternity** [comment]
If this will be implemented in the 'Pawn' class, then there also must be an option added in the sub-classes (such as 'Bot' or 'ScriptedPawn') that would allow admin to decide whether this implementation is enabled or not. Otherwise this may cause problems...

This probably was deliberately designed this way, because of the lack of AI complexity.
No 'Bot' nor 'ScriptedPawn' have any mechanism to recognize and to avoid an interaction with this kind of movers, and most of the maps do not have any built-in logic that would make these Pawns aware about such movers that either should not be touched at all (e.g., traps, etc.), or should be touched in the proper way (e.g., lifts).

**Comment by CacoFFF** [comment]
Some pawns are not meant to be killed.
If other pawns need this implementation, it'll be in their respective classes.

**Comment by an-eternity** [comment]
So, mapper should use EncroachDamage rather than (or in addition to) MoverEncroachType, if such kind of mover is needed in the Level.

https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Engine/Mover.uc#L591
