### ISSUE TITLE
[469b] Game either Lags or Crashes When Trying to Join Certain DM Servers

### ISSUE THREAD

**Issue by joefil1991** [OldUnreal/UnrealTournamentPatches#442]
Recently, I updated my game to the 469b patch from 451. Ever since I've done this, I get stuck at "CONNECTING" when trying to connect to most deathmatch servers or the game will crash with the error message attached. When I am able to connect to a server, the game will function just fine. I had no issues with 451 - these all started after updating to the 469b patch.

![error](https://user-images.githubusercontent.com/85605948/121304546-79f54c00-c8ca-11eb-9332-e7a9d9dc7987.png)

Thank you.

EDIT: As requested, here are some servers I was having issues with joining: 

- unreal://185.107.96.109:3529
- unreal://185.107.96.109:3700
- unreal://185.107.96.109:3519
- unreal://185.107.96.109:3710

Interestingly enough, it appears these 4, which are some of the most populated DM servers, are all ran on the same box with different ports. I didn't realize this before.

**Comment by SeriousBuggie** [comment]
Please add list of few address on which problem occurs. 3-5 items.

**Comment by stijn-volckaert** [comment]
This happens when you have a local package that is network-incompatible with a package the server uses. The usual fix is to delete your local version of the package, so the game will download the server's version instead. There are a few known culprits, but none of them are included in the 469b patch:
- De.u: there are 3 known versions of this file, and 1 of them is incompatible with the other 2 versions
- EnhancedItems.u: there are many versions and 1 is incompatible with all others
- There are also a couple of NewNet packages that are known to cause this problem

Another possibility is that your 469b client is still using (some) 451 packages. Did you install 469b over 451 or did you install it in a separate System folder? If you installed it in a separate system folder, you might want to check if you have the correct folder listed in UnrealTournament.ini in the [Core.System] section.

**Comment by NeonKnightOA** [comment]
About de.u: it's from the DE Bonus Pack/Bonus Pack 2. It was originally a standalone release (zip/umod), but the original release was buggy, so a fixed version was later released and then bundled with CTF-HallOfGiants and CTF-Orbital in a single package, and _then_ included in the GOTY Edition.

IMHO considering it's an official package, the latest version of de.u should be included with the patch, as to avoid future problems.

**Comment by joefil1991** [comment]
I updated the original post with the servers I'm having issues connecting to. Additionally, where can I find the latest/correct versions of the de.u and EnhancedItems.u packages? Are there any other packages I should update? This was installed over 451, so I'm wondering if there are some version mismatches. Thank you.

**Comment by joefil1991** [comment]
Also, when trying to connect to those servers, all required files will download but UT99 will still get stuck as "CONNECTING."

**Comment by joefil1991** [comment]
@stijn-volckaert You were completely right. I found a newer version of de.u, de.int, and the EnhancedItems mutator. These servers are now all working correctly. Thank you for the help, all! I'll reopen this if I have any other related issues.
