### ISSUE TITLE
[469b] Class with config fields and without config declaration not load defaults from INI

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#487]
```
class CoopTranslocator extends Translocator;

var() globalconfig string Command;
var() globalconfig int DisableUseTime;
```
This class when built via v436 load default from main INI file.
When built via v469b not load defaults from main INI file.
If I change it to:
`class CoopTranslocator extends Translocator config(System);`
Then build from v469b will be fine.

**Comment by stijn-volckaert** [comment]
This is a side effect of a change we made to the translocator. When we made said change, we also specified User.ini as the storage location for Botpack.Translocator's settings. Since CoopTranslocator does not specify a storage location, it inherits User.ini from Botpack.Translocator. Changing Botpack.Translocator's ini to UnrealTournament.ini would not make much sense as all other weapon settings are stored in User.ini. Furthermore, we would have to migrate the existing settings from User.ini to UnrealTournament.ini. In this case, I would recommend fixing the mod instead.
