### ISSUE TITLE
[469b] D3D9 not able init render full-screen if windowed mode too small

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#488]
Reproduce:
1. Start UT with D3D9 renderer,
2. Press Alt+Enter for go to windowed mode.
3. Make very small height of window.
4. Press alt+Enter again for return t full screen mode.

Expected result: Game return to full-screen.
Actual result: Screen not rendered.

You can return back to windowed mode increase height of window and normally goes to full-screen.

Possible cause because firstly set full-screen mode, and only after that resolution. So video hardware not able goes to so small resolution.

**Comment by SeriousBuggie** [comment]
Happen not always. And possible drivers related.
Possible not worth fix it at all.

**Comment by an-eternity** [comment]
Same result on my side, and the game is crashed with error:
![ut99_v469b_alt+tab_small-res_bug](https://user-images.githubusercontent.com/72374425/125512816-33378917-f6fa-4a12-96e9-1271ce4b4c18.png)

Sometimes, very rarely, after switching from windowed mode (that has normal resolution, not lower than 1024x768) to full screen mode something wrong happens with the hardware driver... The screen remains black then, even after using Alt+Tab and Ctrl+Alt+Del. The only way to bring it back is the Reset button or the Remote Desktop... This happens only with UT99.
The hardware is from AMD and traditionally has awful drivers with lots of bugs... So maybe this problem is driver related.

**Comment by stijn-volckaert** [comment]
This is a driver issue that we have little control over. I'm not sure if there's anything we can do to mitigate the problem either

**Comment by SeriousBuggie** [comment]
Driver specific bug.
Driver start flood with WM_MOUSEMOVE messages.
Driver think mouse not in proper place, even if it already be.
So it just post WM_MOUSEMOVE again and again.
Such flood completely kill render, since all time wasted for process WM_MOUSEMOVE messages.

As possible workaround can be resize UT window before goes fullscreen.

**Comment by an-eternity** [comment]
Can't reproduce nor black screen neither crash in updated test environments - Win10/11 22H2, with various AMD GPU drivers from version 22.11.2 to 23.2.2.

**Comment by SeriousBuggie** [comment]
Possible nvidia issue.
