### ISSUE TITLE
[469b] UnrealEd produce deadly spots near invisible surfaces in some cases

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#554]
1. Open [MH-HP2-GrandStaircaseV3_bug.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7198963/MH-HP2-GrandStaircaseV3_bug.zip) in UT.
2. You can respawn in any of 3 point.
3. Just go forward and jump into dark place.

Expected result: You not die.
Actual result: you die. 

![img](https://user-images.githubusercontent.com/70026933/134083061-3e21d933-f6cf-4477-a981-b3deeba0fffa.png)
![img](https://user-images.githubusercontent.com/70026933/134083176-bd5b422c-e41f-478d-8f94-4073dce3cc1a.png)
![img](https://user-images.githubusercontent.com/70026933/134083265-3d60117a-1a25-45cb-b0d8-e5848da587fd.png)

If map rebuilt with settings 100/75 - dead spot gone.

**Comment by SeriousBuggie** [comment]
> If map rebuilt with settings 100/75 - dead spot gone.

Appear in different place
![img](https://user-images.githubusercontent.com/70026933/134112013-ba91b2c3-1641-4b3e-a6e5-1c12ae2e56d2.png)

**Comment by SeriousBuggie** [comment]
There little better for debug version
[MH-HP2-GrandStaircaseV3_bug2.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7203231/MH-HP2-GrandStaircaseV3_bug2.zip)

Better look texture. And all added semi-solid brushes added into group `deco`.
Also dropped one `SG_Active` brush, which not affect to issue at all.

**Comment by Feralidragon** [comment]
Fixed:
[MH-HP2-GrandStaircaseV3_bug2_fixed.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7206070/MH-HP2-GrandStaircaseV3_bug2_fixed.zip)

This map has a lot of stuff off-grid, sheered at least in one of the axis, etc, and although semis were used often, there are plenty of places where solids could be turned into semis.

The main issue with these blocks causing the death spots is due to the way they were built in the first place:
- if you look at the ones from the first screenshot (for example), using the 2D Front view, you will notice that they are slightly sheered towards the X axis, so they're not aligned with anything at all;
- they completely unaligned in relation to other brushes, and completely off-grid for no good reason.

In the case of the first screenshot, I did try a few things first (ordering solids differently in that room for example), but nothing worked, and then I moved the problematic brush around and the problem moved with it as well, meaning that the brush itself was the problem.

So what I did in that case was to recreate the brush, and create it properly: with the same dimensions, and placed at the same spot, but this time without any sheer and perfectly aligned to the grid, using a 8uu grid, and after the rebuild the problem went away instantly.

The problem then moved to the other brush on the opposite wall, so I simply deleted that brush, and duplicated and flipped the fixed one, and placed it where the old one was, and hold and behold, problem fixed on that one as well.

On the other 2 cases from the other screenshots, I didn't need to rebuild the brushes properly, all I did was turn the brushes Brush216 and Brush269 to semi-solid, and after the rebuild the problem went away immediately as well.

Everything in these areas seem to be fine now, without death spots, nor any collision or occlusion issues of any sort, that I have noticed at least.

I did a "Build All" for every rebuild, and I used nothing by the default BSP build settings (no special settings were needed at all).

Either way, the conclusion is simple: the brushes giving problems are the ones that are not built properly, so in these cases the best thing to do is to recreate them in the same way I did in the first case, which fortunately in all these cases they all seem to be very simple brushes, so they can be easily recreated (it took me seconds to recreate the ones in the first screenshot).

**Comment by SeriousBarbie** [comment]
That's also my experience, especially with maps created by others: after deleting and recreating a brush (or mover) the problem disappears.

**Comment by SeriousBuggie** [comment]
Minimal reproducible example (for hunt down bug in engine):
![img](https://user-images.githubusercontent.com/70026933/134251138-c7cbf3b6-8c00-40a8-86be-7c0fb6e90d26.png)
![img](https://user-images.githubusercontent.com/70026933/134251171-8288ee34-1787-4be2-9b66-7a3030ac7151.png)
Only 4 brushes.
[MH-HP2-GrandStaircaseV3_bug3_hp2_crop7.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7206441/MH-HP2-GrandStaircaseV3_bug3_hp2_crop7.zip)

**Comment by Feralidragon** [comment]
If you zoom in into those 2 small brushes using the 2D Front view, you will notice that they are also very slightly sheered towards the X axis, meaning that the brushes themselves are badly built.

As a matter of fact, I did a few tests, and if you turn those 2 brushes to either solid or non-solid, the exact same issue happens, meaning that the problem has nothing to do with solidity, it has everything to do with the shape of the brush.

Either way, this is a good case of study to understand what exactly is going wrong in this type of case.

**Comment by SeriousBuggie** [comment]
Shape is fine. Rortation is not "good":
![img](https://user-images.githubusercontent.com/70026933/134260463-9a483163-86c2-4076-a10e-b43b2d8cf2e1.png)
![img](https://user-images.githubusercontent.com/70026933/134260577-6a6636ed-2942-4ddd-ac0d-17dbf4927f36.png)
16384 is "better" value. But this fix solve nothing.

In fact problem cause by brush PolyFlags = 1
`PF_Invisible		= 0x00000001,	// Poly is invisible.`
If i remove from both brushes this flag all fine.

So i turn both to solid and make on one top side is invisible.
![img](https://user-images.githubusercontent.com/70026933/134262184-ca2d84c3-9239-465d-a6ce-9160fba0de64.png)
![img](https://user-images.githubusercontent.com/70026933/134262204-31608351-8ed3-4c75-b783-c8899c20b5d5.png)
Look like somehow invisible side make "hole" from which void leak into real space.
Possible optimization choose from two coplanar polys wrong one which lead to "leak" void.
[MH-HP2-GrandStaircaseV3_bug3_hp2_crop8.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7206860/MH-HP2-GrandStaircaseV3_bug3_hp2_crop8.zip)
Look like other brushes need for create special condition for bug appear.

**Comment by SeriousBuggie** [comment]
![img](https://user-images.githubusercontent.com/70026933/134265175-7fd9c1cd-96e1-4a9d-bc67-c4b232847d84.png)
Portals if surface visible.
![img](https://user-images.githubusercontent.com/70026933/134265236-b2fd0cf1-b718-4ab0-bb0b-9184a7f83349.png)
Portals if surface invisible.
Invisible surface stop limit portal so it end inside brush and hull not created. So inside void.

**Comment by SeriousBuggie** [comment]
Now  I know what happen.

> MH-HP2-GrandStaircaseV3_bug2_fixed.zip

First two brushes you make fully visible. So this not solution at all.
Its visible in game mode:
![img](https://user-images.githubusercontent.com/70026933/134268827-e1a884c7-c172-44d3-969c-820d500a0623.png)

For next two brushes problem masked.
![img](https://user-images.githubusercontent.com/70026933/134269030-4e9be8c0-97a7-436d-aedc-c4629f0823d6.png)
![img](https://user-images.githubusercontent.com/70026933/134269063-7238091d-015c-4791-86a1-026c22f474ca.png)
Portals split by brush edge. But this not permanent. this is temporary condition. You add any other brush, possible even not in this room, BSP will be rebuilded, edge of portal goes into void, check for fill portals start from another poly, issue return back.

BSP can be rebuilt just because too deep. So it look like you make complicate stuff far-far away, but there appear death spots.

As I see, no currently solutions for this. So avoid use invisible surface at all costs. At least until not out UnrealEd which able properly handle it. But even in this case, better not do this, for allow rebuild your maps in older versions.

**If you need invisible wall not use invisible flag. Set it to empty masked texture.** As show tests event not need set masked flag to surface (this possible can cause possibility shoot through this surface - not sure).
Here such "invisible" surface:
![img](https://user-images.githubusercontent.com/70026933/134270191-2ddb2e5d-9bd4-4fe0-be50-b067321d4642.png)
For select it you need switch to texture mode:
![img](https://user-images.githubusercontent.com/70026933/134270265-f372aa58-5c76-4e47-883f-4c93b9cdd59b.png)

Possible in v469c this issue will be fixed. Anyway better not use invisible surfaces at all. Exception only for flat brushes because flat brushes ignored (AFAIK) for determine edge for split space on portals. In any case if even split goes wrong nothing bad happen, because no any inner space.

Make brush non-solid not help:
![img](https://user-images.githubusercontent.com/70026933/134271343-d0bb6534-ae90-40e4-8393-454140555e11.png)

> However, I have also found out that setting the surface to both Invisible and Portal fixes the issue.

Confirmed. But I not be rely on this. Look like portal flag force split on full size of portal poly. But this can be wrong in some cases. In this simple case when shape of poly easy it work. But i doubt about that if poly shape be complex.

> Weirdly though, removing the Invisible flag from the surface, rebuild, and then setting it again, and rebuild again, fixes the issue too...

For me not help. Look like you forget select surface after rebuilt. Any rebuilt make selected surfaces invalid. So need reselect it.
Best check for invisible surface or not - it disappear in game mode if you not in void.

**Comment by SeriousBuggie** [comment]
Anther example of bad split volume: https://ut99.org/viewtopic.php?f=5&t=15469&sid=4b7cd404a1854ffca43be31205425fcb
There few test maps which can be useful for debug issue and fix it.

**Comment by no0nehere** [comment]
i have similar issues here; https://ut99.org/viewtopic.php?f=5&t=15469&sid=17bbfcdfa79dfabbe15c162da1a79cb7
