### ISSUE TITLE
[469b] Monsters ignore Movers on a dedicated server

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#559]
Original issue: https://www.oldunreal.com/phpBB3/viewtopic.php?f=42&t=4521
Reproduce:
1. Start on dedicated server [DM-!!!shoot_dedic_bug.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7256564/DM-.shoot_dedic_bug.zip)

Expected result: Kralls not try shot on you.
Actual result: Kralls try shot you.

Right krall subclassed:
```
simulated event Tick(float delta)
{	
	local vector      HitLocation;
	local vector      HitNormal;
	Super.Tick(delta);
	
	if (Enemy == None)
		return;
		
	Log(Name @ "->" @ Enemy.Name @ 
		"FastTrace =" @ FastTrace(Enemy.Location, Location) @ 
		"Trace(false) =" @ Trace(HitLocation, HitNormal, Enemy.Location, Location) @ 
		"Trace(true) =" @ Trace(HitLocation, HitNormal, Enemy.Location, Location, true) @ 
		"TraceShot =" @ TraceShot(HitLocation, HitNormal, Enemy.Location, Location) @
		";"
		);
}
```
Debug output:
```
ScriptLog: MyKrallElite0 -> TFemale0 
FastTrace = True 
Trace(false) = DM-!!!shoot_dedic_bug.Mover0 
Trace(true) = DM-!!!shoot_dedic_bug.Mover0 
TraceShot = DM-!!!shoot_dedic_bug.Mover0 ;
```
`FastTrace` description:
```
// returns true if did not hit world geometry
native(548) final function bool FastTrace
```

So as can bee se Fast Trace not Take Movers into account. Maybe can possible implement part from "Trace" call (or from TraceShoot, which use TraceActors iterator):
```
/* TraceShot - used by instant hit weapons, and monsters
*/
function actor TraceShot(out vector HitLocation, out vector HitNormal, vector EndTrace, vector StartTrace)
{
	local Actor A, Other;
	
	ForEach TraceActors( class'Actor', A, HitLocation, HitNormal, EndTrace, StartTrace)
	{
		if ( Pawn(A) != None )
		{
			if ( (A != self) && Pawn(A).AdjustHitLocation( HitLocation, EndTrace - StartTrace) )
				Other = A;
		}
		else if ( (A == Level) || (Mover(A) != None) || A.bProjTarget || (A.bBlockPlayers && A.bBlockActors) )
			Other = A;

		if ( Other != None )
			break;
	}
	return Other;
}
```
for use in Fast Trace for dedicated server.

**Comment by SeriousBuggie** [comment]
Not sure, but possible splash damage too ignore movers by same reason on dedicated server.
Sol possible too need fix or can be fixed at once.

**Comment by an-eternity** [comment]
Some time ago we have added similar fix for the 'Bot' class in GameType, months of tests then have shown it works just perfectly, the results are mostly positive. But i still have doubts if there can be similar good solution for this issue with the 'ScriptedPawn' class practically implemented without breaking anything else...

1. First concern about it is the performance - what will we have in those maps where hundreds of scripted pawns in a large areas are simultaneously trying to attack the players, where we already have up to e.g. 50% of CPU load produced by these pawns... If this fix will cost of at least 15-20 more percents in such cases, then it definitely does not worth it. The question is how much is the performance difference between "FastTrace" and "TraceActors", and will "TraceShot" function be called often enough for this performance difference to produce significant additional CPU load in a result...
2. Second - it will change a lot of things about 'ScriptedPawn' behavior in many maps, it is a kind of unclear matter if this behavior will be actually better in all the cases. Some maps for sure will become much easier to pass, and some players may dislike it.

Also there could be some else related issues except these 2...

Based on these 2 points, i think this fix has to be configurable, so that depending on the particular map we could have it enabled or disabled.

**Comment by SeriousBuggie** [comment]
You not see all info in issue. Some info related to native parts.
So this issue must be fixed in native part.

About changing gameplay: it is mostly same as before and exact same as in `Standalone` mode or `Listen`.
So I not see a big problem with it.

About performance. Need check it. But I doubt if FastTrace implementation eat 50% CPU. So we can make more then 20% increase CPU work. In fact additional check need only if current FastTrace return true.
After that in some way we check line against movers. Possible via some hash structure, which pretty fast, because we not iterate over all movers. Most time we not iterate over movers at all.
So difference in performance can be neglible.

OFC this fix can be make configurable from scripts, with check on native side. Check one bool is pretty fast and not affect performance at all.

**Comment by SeriousBuggie** [comment]
Possible implementation:
By default track is on. For turn off (for get bad old behavior) need edit INI file:
```ini
[Engine.GameEngine]
TrackMoversOnDedicatedServer=False
```

**Comment by SeriousBuggie** [comment]
Option renamed to UseNetMovingBrushTracker and disabled by default.
So for turn on fixed behavior you need set
```ini
[Engine.GameEngine]
UseNetMovingBrushTracker=True
```

**Comment by lafoxxx92** [comment]
Hi I need to enable this option but it's not in User.ini or UnrealTournament.ini
Through console it says unrecognized class
469e release

added:
nevermind it works now
