### ISSUE TITLE
[469b] Function Botpack.ut_biorifle.PlayAltBurst:000B) Accessed None 'Owner'

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#566]
If ut_biorifle is given to a ScriptedPawn (SkaarjGunner for example), the above warning is issued on every burst:
Solution (untested): in function Botpack.ut_biorifle.PlayAltBurst() change
```
simulated function PlayAltBurst() {
	PlayerPawn(Owner).ShakeView(ShakeTime, ShakeMag, ShakeVert);
	if ( Owner.IsA('PlayerPawn') )
		PlayerPawn(Owner).ClientInstantFlash( InstFlash, InstFog);
```
to
```
simulated function PlayAltBurst() {
	if ( Owner.IsA('PlayerPawn') )
	{
		PlayerPawn(Owner).ShakeView(ShakeTime, ShakeMag, ShakeVert);
		PlayerPawn(Owner).ClientInstantFlash( InstFlash, InstFog);
	}	


```

**Comment by an-eternity** [comment]
Is there any reason to not use `PlayerPawn(Owner)!=None` instead of `Owner.IsA('PlayerPawn')`?
I have seen this approach in a lot of classes, but never could figure out what is the reason... I think there is something i don't understand... Since long time ago there is still an undone item in my to-do list to test it some day - to check if maybe it works faster this way... What else could be a reason?

This question would be skipped and forgotten at all... But....
We already have encountered such issues as this in past, e.g.:

```
If (Other.IsA('B_MonsterLoopSpawner'))
{
	i=B_MonsterLoopSpawner(Other).SpawnNum;
}
```

Such script as this one will produce "Accessed None" errors in some cases... Because, unfortunately, some maps load this class from "BBoyShars" package, and another maps load it from "BBoyShare" one.
There are numbers of such examples, e.g., with class 'Predator', etc...

Of course, hopefully, nobody will try to create a third-party package that contains a class named 'PlayerPawn', but anyway i would like to find an answer to this question...

**Comment by SeriousBuggie** [comment]
Error can occur. Let's imagine exists two actors from same binary package but from different names.
`Other.IsA('B_MonsterLoopSpawner')` - true.
`B_MonsterLoopSpawner(Other)` - None because you try cast BBoyShars.B_MonsterLoopSpawner to BBoyShare.B_MonsterLoopSpawner.

**Comment by SeriousBarbie** [comment]
Do you mean that both packages are loaded at the same time? Do mapper really do something? And is it really possible to have actors instances with the same class name from different packages? TriggerLight comes into my mind…
