### ISSUE TITLE
[469b] SSE2 required on Linux and Windows XP

### ISSUE THREAD

**Issue by CommonLoon102** [OldUnreal/UnrealTournamentPatches#587]
Can you please build `ut-bin-x86` and `Core.so` and everything else without SSE2 instructions? It is crashing on my Athlon XP in `Core.so` due to `Illegal instruction`. GDB tells me it tries to use `movsd` which is an SSE2 exclusive instruction and Athlon XP doesn't have it. The original game didn't have a requirement on SSE2.

**Comment by CommonLoon102** [comment]
By the way, what is the difference between `ut-bin` and `ut-bin-x86`? The two files are identical.

**Comment by uralets** [comment]
Don't think there's any diff... that's why they're identical. Both just always have been there.
As for the subj, doubt supporting 2 decade old hardware is high on the dev's agenda. They're stretched as it is.

Linux 64 bit build OTOH would be highly appreciated. Esp. seeing how the M1 support is already planned :\

just my 2 cents.

**Comment by stijn-volckaert** [comment]
The two files are indeed identical. ```ucc-bin-x86``` exists because we can produce statically linked versions of ut-bin and ucc-bin and we can target other architectures as well. With the architecture suffix in the file name, the different versions of the game can coexist in the same folder.

We added ```ucc-bin``` at some point during the early beta tests because previous versions of the game used that name and several of our testers couldn't update the launch script for their servers to point it to the new binary.

Regarding support for older/newer platforms: we are a very small team with limited resources. We can only afford to support platforms that are widely used. x86 CPUs without SSE2 support are virtually "extinct" in 2021 so it makes little sense to support those (and several of our dependencies won't work without SSE2 anyway). Apple M1 support, on the other hand, is definitely happening because many mac users are switching or have already made the switch to the new architecture.

We _could_ also release the game for x86_64 Linux systems if there's high demand for it.

**Comment by CommonLoon102** [comment]
Compiling without SSE2 is just setting a compiler switch. What dependencies won't work without SSE2?

**Comment by CommonLoon102** [comment]
There are 246 `movsd` in `Core.dll` what is included for the Windows XP version.

**Comment by stijn-volckaert** [comment]
Enabling SSE2 code generation gives us substantial performance benefits. To support older architectures, we either need to take a performance hit or build a separate patch. In both cases, the drawbacks far outweigh the benefits.

Retro gamers can still play this retro game on their retro PCs, but they have to use older versions of the game. Our goal were to (1) improve the gaming experience for the vast majority of gamers that play on more modern systems, and (2) ensure that our patch remains network-compatible with the original version. I believe we achieved that.

The Windows XP version of the patch is identical to the regular version, except for one file. We included an older OpenAL32.dll in the Windows XP patch because OpenAL-Soft dropped XP support a while back. We are seriously considering dropping XP support ourselves, however, because XP support in Visual Studio has been deprecated for a while now and the deprecated v140_xp and v141_xp toolsets have had several major code generation bugs in recent MSVC releases.

**Comment by CommonLoon102** [comment]
> To support older architectures, we either need to take a performance hit or build a separate patch. In both cases, the drawbacks far outweigh the benefits.

Adding a few extra lines to the build script isn't really a huge thing. If it was open source, I'd do it, but it isn't...

**Comment by uralets** [comment]
> Apple M1 support, on the other hand, is definitely happening because many mac users are switching or have already made the switch to the new architecture.
> 
> We _could_ also release the game for x86_64 Linux systems if there's high demand for it.

A bit disappointing way of thinking tbf.
While Apple users "are switching or have already made the switch", we Linux users made it en masse quite some time ago.
So you could count any demand for a Linux build as a x86_64 one. OTOH one would have to really dig to come up with examples for a massive need for a 32 bit build, maybe folk with old(ish) servers hosting games or something...

So basically if you're to satisfy demand for a Linux build it's imperative to have a 64 bit one these days. It'll instantly boost the accessibility for like 99% of your Linux users.

Hope you really look into getting it done!

**Comment by stijn-volckaert** [comment]
Windows and Linux systems can run the 32-bit version natively and without any performance loss, though. That's different on Macs. Apple simply stopped supporting 32-bit apps in 10.14 (?) and the 64-bit Intel version is not playable on M1 macs.

**Comment by CommonLoon102** [comment]
So which dependencies cannot be rebuilt without SSE2? Maybe they are not needed. If new renderers and audio system requires it, just don't use it. I could see settings like `Use SSE2` for some renderers when I opened `preferences` from the terminal (on Windows).

The only thing needed is to add USE_SSE2 parameter to the build script and that's it. Not really a big task.

**Comment by uralets** [comment]
I imagine eDuke32 has an order of magnitude larger team looking after it.
Any change introduced esp at such a low level requires thinking-implementing-testing-thinking over-more testing-etc. You know it if you've done any sort of development.
Anyway why do you insist on targeting 20yo hardware by a very limited dev team? Bit of a luxury (pun intended) if you ask me.
The stupid NDA sucks but it is what it is.

Enough of me hijacking the thread.
I'll just shamelessly reference #535

**Comment by CommonLoon102** [comment]
> Anyway why do you insist on targeting 20yo hardware by a very limited dev team? Bit of a luxury (pun intended) if you ask me. The stupid NDA sucks but it is what it is.

Because fixing this issue might be a very simple thing, and then the game would be able to run on those machines which it was intended to be run on originally.

I have 17yo hardware, still it can run up-to-date OS and browser on it with the latest security patches. But it cannot run a 22yo game. Strange.

**Comment by CommonLoon102** [comment]
> I imagine eDuke32 has an order of magnitude larger team looking after it.

Order of magnitude means 10 times more, right? I doubt it. I know the devs and there are about 4-5 permanent active developers at most.

**Comment by uralets** [comment]
> Because fixing this issue might be a very simple thing,
Not when you already have more than enough on your hands.

> and then the game would be able to run on those machines which it was
> intended to be run on originally.
This version wasn't. It's simple as that. You could just run the
original if you so please.

> I have 17yo hardware, still it can run up-to-date OS and browser on
> it with the latest security patches. But it cannot run a 22yo game.
My version was you're some sort of a VOGONS-dwelling geek building old
rusty and completely undistinguished run-of-the-mill PC rigs (complete
with an ELT monitor that gives you the headache) just TO-PLAY-LIKE-IT-
WAS-MEANT-TO-BE-PLAYED!!!11

**Comment by uralets** [comment]
> > Order of magnitude means 10 times more, right? I doubt it. I know the
> devs and there are about 4-5 permanent active developers at most.

Even so. You've quite covenietly let out some important factors that
set these projects apart. Consider how long eduke is around for one.
How many ppl have worked on it? Those man-months you know. I think even
Ken himself contributed. How many iterations it came through. At least
2 renderers for example. I'm no expert on eduke but I know that much.
Or the simple fact that Build and some of the associated games are
actually open sourced for some time now.
You don't have to have 50 active devs at any given time to have 10
times dev love dedicated to the project. And then there are testers
(users) and what not. Various side projects (that guy doing Java based
ports, that still run off eduke renderers). In a word - ecosystem. This
is a much smaller endeavor unfortunately for the reasons we know but
can't do much about rn.
Your case btw reinforces my point - you've said you'd do it it was
open. You'd contribute but you might never work on it again - thus you
won't count as a permanent dev. Yet that'd fix the issue.

**Comment by CommonLoon102** [comment]
> You could just run the original if you so please.

Can you please point me to the original Linux binaries then?

> This version wasn't. It's simple as that.

I thought this project's aim is to make UT run on more stuff than it was able to run before. This is why there are binaries for Mac and Linux. And on new hardware in general (M1). And on not so new hardware as well, because at 2000 FPS the game behaves crazy.
So I understand why it supports things what it haven't supported before, but dropping and breaking things what were working before is something what worth an issue on GitHub.

**Comment by uralets** [comment]
> > Can you please point me to the original Linux binaries then?

without even leaving github
https://github.com/liflg/unreal.tournament_451-english_x86

tho if you're running a modern stack you're bound to run into the same
difficulties with it as everyone else. YMMV.

**Comment by CacoFFF** [comment]
Not going to happen.

1 - There was a ton of hacky code designed to bypass FPU instructions by loading numbers into the normal CPU registers, this code isn't good at all when your compiler is considering SSE2 instructions... and when you're building on ARM+NEON systems, so we simply removed it.

2 - I wrote a SSE2 library for x86 versions of the game, particularly in LINUX where we had the liberty of using SIMD instructions for the 3 component vector math, given that the game does a lot of rendering in the CPU, we had an instant performance boost of about 10% when compiling the game with such changes, much higher in some areas with specific dynamic light effects. *

3 - The OpenGLDrv render device has been almost completely rebuilt, and shares barely 5-10% of the UTGLR builds' code. One of the biggest changes is that it no longer uses the ancient OpenGL fixed pipeline, the GPU/drivers on that system must support shaders (GL_ARB_FRAGMENT_PROGRAM) as a minimum requirement.
(And because fixing bugs on the fixed pipeline is one of the most horrible and most limiting experiences)

4 - You'd also have to make sure that you're using a non-SSE OpenAL32 library or you will be out of luck when trying to run ALAudio.

* Yes, the native Linux build has much wider usage of SSE2 instructions than the Win32 one, and indeed runs faster on the same dual boot system.
