### ISSUE TITLE
[469b] wx-ut-bin doesn't work with WxGTK3 3.0.5 (stable) and 3.1.5 (devel)

### ISSUE THREAD

**Issue by ivdok** [OldUnreal/UnrealTournamentPatches#590]
Arch Linux with either wxgtk3-3.0.5.1-2 (latest packaged) or wxgtk3-dev-3.1.5-2 (self-compiled) will throw following error on launching wx-ut-bin:
`./wx-ut-bin: error while loading shared libraries: libwx_gtk3u_core-3.1.so.4: cannot open shared object file: No such file or directory`
Judging by the printout, and the listing of WxWidgets' libs:
`$ ls /usr/lib/libwx_
libwx_baseu-3.1.so                 libwx_gtk3u_adv-3.1.so.5           libwx_gtk3u_gl-3.1.so.5.0.0        libwx_gtk3u_qa-3.1.so              libwx_gtk3u_stc-3.1.so.5
libwx_baseu-3.1.so.5               libwx_gtk3u_adv-3.1.so.5.0.0       libwx_gtk3u_html-3.1.so            libwx_gtk3u_qa-3.1.so.5            libwx_gtk3u_stc-3.1.so.5.0.0
libwx_baseu-3.1.so.5.0.0           libwx_gtk3u_aui-3.1.so             libwx_gtk3u_html-3.1.so.5          libwx_gtk3u_qa-3.1.so.5.0.0        libwx_gtk3u_webview-3.1.so
libwx_baseu_net-3.1.so             libwx_gtk3u_aui-3.1.so.5           libwx_gtk3u_html-3.1.so.5.0.0      libwx_gtk3u_ribbon-3.1.so          libwx_gtk3u_webview-3.1.so.5
libwx_baseu_net-3.1.so.5           libwx_gtk3u_aui-3.1.so.5.0.0       libwx_gtk3u_media-3.1.so           libwx_gtk3u_ribbon-3.1.so.5        libwx_gtk3u_webview-3.1.so.5.0.0
libwx_baseu_net-3.1.so.5.0.0       libwx_gtk3u_core-3.1.so            libwx_gtk3u_media-3.1.so.5         libwx_gtk3u_ribbon-3.1.so.5.0.0    libwx_gtk3u_xrc-3.1.so
libwx_baseu_xml-3.1.so             libwx_gtk3u_core-3.1.so.5          libwx_gtk3u_media-3.1.so.5.0.0     libwx_gtk3u_richtext-3.1.so        libwx_gtk3u_xrc-3.1.so.5
libwx_baseu_xml-3.1.so.5           libwx_gtk3u_core-3.1.so.5.0.0      libwx_gtk3u_propgrid-3.1.so        libwx_gtk3u_richtext-3.1.so.5      libwx_gtk3u_xrc-3.1.so.5.0.0
libwx_baseu_xml-3.1.so.5.0.0       libwx_gtk3u_gl-3.1.so              libwx_gtk3u_propgrid-3.1.so.5      libwx_gtk3u_richtext-3.1.so.5.0.0  
libwx_gtk3u_adv-3.1.so             libwx_gtk3u_gl-3.1.so.5            libwx_gtk3u_propgrid-3.1.so.5.0.0  libwx_gtk3u_stc-3.1.so          `
I'm guessing whoever made this launcher:
1. Used developers' branch instead of stable one
2. And even then, binded to specific version's soname instead of using generic ABIs (e.g. the ones that end with 3.1.so).

Questions is, why? What merits using yet-unreleased branch, and binding to specific version that is subject to obsoletion? As a result, it's quite non-trivial to run this version to access advanced settings.

**Comment by CommonLoon102** [comment]
I have the same issue and `ldd ./wx-ut-bin` tells me that 2 libwx related are deps are missing. Trying to get them now.

**Comment by SeriousBuggie** [comment]
1. Crappy way of WxWidgets versioning. This "stable" version not usable at all. Too many bugs. So no any chance use it.
Also they say "dev" version is "stable" enough for use.
2. You need use wxWidgets 3.1.4, because they not really maintain binary compatibility across versions.
Look here: https://abi-laboratory.pro/index.php?view=objects_report&l=wxwidgets&v1=3.1.2&v2=3.1.3
There report for 3.1.2 vs 3.1.3, but no any doubt with 3.1.4 vs 3.1.5 all be same.
So if you want work version of binary you need same version.

Also this is default behavior for linker - link to exact version of binary which exists in system.
Binary compiled with general flags like `-lwx_gtk3u_xrc-3.1 -lwx_gtk3u_html-3.1 -lwx_gtk3u_qa-3.1 -lwx_gtk3u_core-3.1 -lwx_baseu_xml-3.1 -lwx_baseu_net-3.1 -lwx_baseu-3.1`.

If you really miss adventure in your life, you can try add missing dependency by point them to 3.1.5. e.g. 
`libwx_gtk3u_core-3.1.so.4 => libwx_gtk3u_core-3.1.so.5`.
If binary compatibility preserved then this allow run application without problem.
After that we can consider some ways for try compile app against libs without versions.

**Comment by CommonLoon102** [comment]
Clearly they didn't hear about semantic versioning.

**Comment by stijn-volckaert** [comment]
The x86 and amd64 patches of 469d will include a wxWidgets 3.2.0-based launcher
