### ISSUE TITLE
[469a] Will D3D9 add the ability to display detail textures in fog zones?

### ISSUE THREAD

**Issue by sn260591** [OldUnreal/UnrealTournamentPatches#65]

**Comment by CacoFFF** [comment]
While both UTGLR renderers (GL and D3D9) *were* very similar at one point, they both shared the limitation of only being able to use up to 4 texture mapping units.

So you have: main texture, detail texture, lightmap, fogmap, macro texture, (and not implemented) bump map.
That's more than 4.
The UTGLR code in both renderers has been written with so many microoptimizations that in order to change something a full redesign in certain areas needs to be done.
I have done some of those redesigns in the OpenGL renderer but not ported any of that to D3D9.
Fixing detail + fog is planned for OpenGL with yet another redesign of the handling of texture mapping units, and again, I don't think I'll end up touching D3D9.

**Comment by racing-online** [comment]
D3D9 by Chris Dohnal was the fastest renderer and had the least problems. It is at that level of perfection where, i bet, further improvement is barely possible. Changing it only to add a new small feature wouldn't be good idea.

**Comment by Dr-Flay** [comment]
The DirectX renderer needs as much attention as GL, because many people use intel or ATI chipsets which are not as compatible with GL.
Unless it has been fixed or bypassed, intel still has 2 HW functions disabled in GL.
ATI cards tend to put the texture data into system RAM instead of GFX RAM when using GL.

**Comment by racing-online** [comment]
> ATI cards tend to put the texture data into system RAM instead of GFX RAM when using GL.

Looks like that's the reason they have twice-triple lower performance with (X)OGL against D3D9-11 renderers.

**Comment by stijn-volckaert** [comment]
We will most likely focus on improving XOpenGLDrv (for modern OpenGL cards) and OpenGLDrv (for older cards) moving forward. @CacoFFF is currently wrapping up a substantial redesign of OpenGLDrv that should improve performance across the board, including for old ATI cards. I'm going to mark this ticket as a wontfix for now. However, we will probably include D3D9Drv in the SDK. If someone wants to implement detail texture support for fog zones, we'd be happy to accept the pull request.

We're planning to release the SDK soon, but we are still working out some details concerning forward compatibility of the 469 rendering interface.
