### ISSUE TITLE
[469b] UnrealEd: Software render fail render some surfaces properly

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#669]
Moved from: https://www.oldunreal.com/phpBB3/viewtopic.php?f=42&t=4485

Reproduce:
1. Open map [DM-!!!!bug_soft_render.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7792614/DM-.bug_soft_render.zip)
2. Switch to software render, Textured mode.

Expected result: All OK.
Actual result: Textures on wall surfaces glitches.
![img](https://user-images.githubusercontent.com/70026933/147746470-63a24e2b-d85b-4c52-839f-72cb7de5ba21.png)

**Comment by stijn-volckaert** [comment]
This seems to happen because of rounding errors in SoftDrv's floating-point<->fixed-point texture coordinate conversion code. Unfortunately, we don't have anyone on the team who actually understands SoftDrv, so I'm going to have to mark this as a wontfix. We can revisit this ticket if Epic ever decides to open source the game.
