### ISSUE TITLE
[469b] move the F6 stats below

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#698]
![Screenshot_1846](https://user-images.githubusercontent.com/58362332/147766248-0679abaf-7e10-4d55-a044-25fc8d1da269.png)

This is an important enhancement fix, a lot of people including me are using F6 to show network stats, but the problem is that they are on top of the chat/kill box and you can hardly see anything. I am seeing people streaming with it on and it's quite annoying to not see the chat box in game. 

It would be nice if the F6 net stats were moved below the chat box.

**Comment by SeriousBuggie** [comment]
Hard to find proper place for it. Space used by different mods very different. Possible via some settings which store offset X and Y.

**Comment by Engineer9736** [comment]
It's about choosing between 2 bad situations: Either having the issue in original UT, or having the issue in some mod for UT.

Then i would say, have unmodded UT look neat. If it disturbs a GUI for some mod then the person playing that mod can turn F6 off. I think having F6 and the chat mixed through each other is worse than having F6 and some graphical icon from a mod mixed through each other. 

Would also be neat if the code for F6 checked if the chat is open, if so, then move it below the chat. Otherwise when the chat is closed, the F6 text would be floating midscreen.

Not sure though if the F6 code can check the GUI details (like chat area status), i think the F6 code is hardcoded in the game source, while the rest of the GUI is UnrealScript. If i grep the System directory on "NET (IN/OUT)" it doesn't find anything, so perhaps it's in some dll in some multibyte format.

Having the X and Y coordinates configurable is also nice, but maybe too technical for the average player. Then it would need a drag-and-drop function to make it user friendly.

**Comment by SeriousBuggie** [comment]
https://www.oldunreal.com/phpBB3/viewtopic.php?p=99743#p99743
> Added in 469c. Under [Render.Render], you can now set:
> 
> - StatOffsetX: X coordinate of the top left corner of the stats display. Default Value: 0
> - StatOffsetY: Y coordinate of the top left corner of the stats display. Default Value: 16

**Comment by stijn-volckaert** [comment]
The new options are in 469c-RC2
