### ISSUE TITLE
[469b] UnrealEd on import transparent PNG ignore alpha channel instead of make fade to black

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#759]
Reproduce:
1. Try Import in UnrealEd texture browser next png:
![jrmskyring](https://user-images.githubusercontent.com/70026933/158131237-7154ecb2-5aa5-4fb1-8428-86959d3b02b2.png)

Expected result: Same if Transparent image put on black background:
![img](https://user-images.githubusercontent.com/70026933/158131574-d409423c-007a-4509-883f-83dc8ae9d0c1.png)
source for achieve this:
![jrmskyring_d](https://user-images.githubusercontent.com/70026933/158131733-90cc1744-298d-43cc-9440-37a3994fd47a.png)
Actual result:
![img](https://user-images.githubusercontent.com/70026933/158131518-e4541291-21be-46fa-b849-5a06c51ba5dc.png)

Current workaround is open image in editor with layers like Photoshop,make black background and save it.

**Comment by SeriousBuggie** [comment]
Additional info: used Software render for get this issue.

If used any other render, and make import as Masked, then result little better:
![img](https://user-images.githubusercontent.com/70026933/169653727-1fb0363d-c840-422b-87f2-d2aaa8c57ab4.png)
But still look like 1 bit transparency, not as alpha channel.
Which is odd since here stated BC3, which must allow 8 bits for alpha channel.

**Comment by stijn-volckaert** [comment]
This issue will be partially fixed in 469c. The problem was that PNG images contain straight alpha colors, but UE1 renderers generally assume that textures with an alpha channel have premultiplied alpha colors. I added the conversion from straight alpha to premultiplied alpha yesterday. If you import the PNG as a masked image, it now looks like this:

![afbeelding](https://user-images.githubusercontent.com/10390414/169974870-2e15e5d6-275c-484e-b722-d66310e7ccdf.png)
SoftDrv

![afbeelding](https://user-images.githubusercontent.com/10390414/169974926-88b51320-786d-4fee-9b80-0df2a11d87b8.png)
OpenGLDrv

![afbeelding](https://user-images.githubusercontent.com/10390414/169974986-ed4b9bd1-781d-4a38-b160-fd2cf5793a9f.png)
XOpenGLDrv (this one looks a bit weird because I have my editor brightness set to a very high value)

![afbeelding](https://user-images.githubusercontent.com/10390414/169975110-0530d38d-12eb-40ed-8d88-99b3ceaf30e1.png)
D3D9Drv

There is another issue, however. When rendering textures or surfaces that have the PF_Masked PolyFlag set, renderers discard all texels with alpha values below 0.5, which @CacoFFF also mentioned in issue #162. This means that the more translucent parts (that have lower alpha values) of this image appear to be missing. 

We can solve this for regular tile rendering (through DrawTile and friends) by setting PF_Highlighted on the texture. When rendering a tile with PF_Highlighted, the renderer still assumes the tile has premultiplied alpha colors, but it will keep all texels with alpha values >= 0.01.

Unfortunately, PF_Highlighted does nothing on surfaces, and the editor even discards the PF_Highlighted PolyFlag when saving textures/surfaces. Some other games (like Unreal 227 and Rune) support the PF_AlphaBlend PolyFlag on surfaces. PF_AlphaBlend also keeps all texels with alpha values >= 0.01, but it also assumes the surface texture has straight alpha colors. UT currently does not support PF_AlphaBlend.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
