### ISSUE TITLE
[469b] Weapon obstructs view

### ISSUE THREAD

**Issue by sinjuangajan** [OldUnreal/UnrealTournamentPatches#767]
![Screenshot_4](https://user-images.githubusercontent.com/4011140/159163225-a7c27c9a-9d6b-471f-a143-3204507e8e79.jpg)

can you guys please fix this view.  weapon hand center. which hides/overlap the crosshair when specs/demo recording.

**Comment by Engineer9736** [comment]
Good chance that this is related to https://github.com/OldUnreal/UnrealTournamentPatches/issues/729 /  https://github.com/OldUnreal/UnrealTournamentPatches/issues/5

**Comment by stijn-volckaert** [comment]
Does this happen with all renderers? If you happen to be using D3D9Drv or OpenGLDrv, could you try enabling the ZRangeHack option in the preferences menu? (use the "preferences" console command to open the menu)

**Comment by Heiland** [comment]
Only happens on XOpenGL renderer.

**Comment by SeriousBuggie** [comment]
I see such only when spectate bot (on d3d9). But possible it more related to other thing.

**Comment by SeriousBuggie** [comment]
Yes. if use v469b as server I see huge weapon over screen:
![img](https://user-images.githubusercontent.com/70026933/172178469-65fd68d0-ef09-440d-bf45-bfd0ff7a093b.png)

I think need fix this stuff in v469c on client side since hardly expect total update all servers to v469c.

**Comment by SeriousBuggie** [comment]
Another replication rule, now from Weapon:
```
	reliable if( bNetOwner && (Role==ROLE_Authority) )
		AmmoType, bLockedOn, bHideWeapon;
```
`bHideWeapon` not replicate over net, so this is reason why it is show.

More interesting thing - why PlayerViewOffset changed on change handness if such value must not replicate here.

Huh. it travel from PalyerPawn.TargetWeaponViewOffset:
```
	unreliable if ( bNetOwner && Role==ROLE_Authority )
		TargetViewRotation, TargetEyeHeight, TargetWeaponViewOffset;
```
Via my spectator, where I bNetOwner.

This value set in native code if remote role is ROLE_AutonomousProxy.
And set on client side via `PlayerCalcViewEx`.

Now I get why bugged values be little different from defaults:
bugged: `PlayerViewOffset=(X=4.000000,Y=0.000000,Z=-2.000000)`;
default: `PlayerViewOffset=(X=4.400000,Y=-1.700000,Z=-1.600000)`
1. Replication eat precise since replicated each component as int.
2. and call:
```js
function setHand(float Hand)
{
	if ( Hand == 2 )
	{
		PlayerViewOffset.Y = 0;
		FireOffset.Y = 0;
		bHideWeapon = true;
		return;
	}
```
set `Y` = 0.

**Comment by SeriousBuggie** [comment]
But main reason goes on this line of setHand call:
`PlayerViewOffset *= 100; //scale since network passes vector components as ints`
This line not called if weapon hidden:
```js
// set which hand is holding weapon
function setHand(float Hand)
{
	if ( Hand == 2 )
	{
		PlayerViewOffset.Y = 0;
		FireOffset.Y = 0;
		bHideWeapon = true;
		return;
	}
	else
		bHideWeapon = false;

	Hand = fClamp( Hand, -1.0, 1.0); // v469 weapon hand exploit fix
	if ( Hand == 0 )
	{
		PlayerViewOffset.X = Default.PlayerViewOffset.X * 0.88;
		PlayerViewOffset.Y = -0.2 * Default.PlayerViewOffset.Y;
		PlayerViewOffset.Z = Default.PlayerViewOffset.Z * 1.12;
	}
	else
	{
		PlayerViewOffset.X = Default.PlayerViewOffset.X;
		PlayerViewOffset.Y = Default.PlayerViewOffset.Y * Hand;
		PlayerViewOffset.Z = Default.PlayerViewOffset.Z;
	}
	PlayerViewOffset *= 100; //scale since network passes vector components as ints
	FireOffset.Y = Default.FireOffset.Y * Hand;
}
```
But on render lately on client it use division by 100 for get real coordinates.
Which goes to almost zero and weapon appear in middle of screen and close all.

**Comment by SeriousBuggie** [comment]
Possible solution.
Since Minigun2, PulseGun, WarheadLauncher not set `PlayerViewOffset.Y = 0;` we can not rely on Y for detection.
I suggest next fix:
```js
if (Abs(PTarget.Weapon.PlayerViewOffset.X - PTarget.Weapon.Default.PlayerViewOffset.X) <= 1.0 && 
	Abs(PTarget.Weapon.PlayerViewOffset.Z - PTarget.Weapon.Default.PlayerViewOffset.Z) <= 1.0)
	PTarget.Weapon.PlayerViewOffset *= 100; //scale since network passes vector components as ints
```
And put it in PlayerPawn.PlayerCalcViewEx:
```js
event PlayerCalcViewEx(out actor ViewActor, out vector CameraLocation, out rotator CameraRotation, out vector CameraVelocity )
{
	local Pawn PTarget;

	if ( ViewTarget != None )
	{
		ViewActor = ViewTarget;
		CameraLocation = ViewTarget.Location;
		CameraRotation = ViewTarget.Rotation;
		CameraVelocity = ViewTarget.Velocity;
		PTarget = Pawn(ViewTarget);
		if ( PTarget != None )
		{
			if ( Level.NetMode == NM_Client )
			{
				if ( PTarget.bIsPlayer )
					PTarget.ViewRotation = TargetViewRotation;
				PTarget.EyeHeight = TargetEyeHeight;
				if ( PTarget.Weapon != None )
				{
					PTarget.Weapon.PlayerViewOffset = TargetWeaponViewOffset;
					if (Abs(PTarget.Weapon.PlayerViewOffset.X - PTarget.Weapon.Default.PlayerViewOffset.X) <= 1.0 && 
						Abs(PTarget.Weapon.PlayerViewOffset.Z - PTarget.Weapon.Default.PlayerViewOffset.Z) <= 1.0)
						PTarget.Weapon.PlayerViewOffset *= 100; //scale since network passes vector components as ints
				}
```
and same in Dying state.

This not hide weapon. It is make centered it, but still visible.

If you need hide weapon, then you in trouble, since there not enough info for know that.

**Comment by an-eternity** [comment]
I remember a long time ago had to set custom value for `Canvas.Z` of HUD in order to fix HUD overlapping problems once and forever, because "ZRangeHack" option in renderers didn't work properly in some cases...

**Comment by SeriousBuggie** [comment]
It is not related to any Z-order problem. There not replicated `bHideWeapon`. So weapon visible.
And since game don't care how placed invisible weapon, it placed like this. Without proper multiply to 100.
