### ISSUE TITLE
[469b] Dodge block duration increases with ping

### ISSUE THREAD

**Issue by mbovijn** [OldUnreal/UnrealTournamentPatches#805]
In the BunnyTrack mod, players with a low ping have a clear advantage over players with a high ping, because dodging doesn't feel as snappy. After having dodged, [0.35 seconds](https://github.com/mbovijn/UT99/blob/master/Engine/PlayerPawn.uc#L4254) need to have passed, before a player can dodge again, but for players with a high ping this value can actually be higher e.g. 0.42 seconds. This is a notable difference, and puts such players in a disadvantageous position when rushing maps where you want to chain dodges as fast as possible.

I did some research into why this is happening, and from what I understand it doesn't seem like a huge thing to fix.
https://github.com/mbovijn/BTPog/blob/master/DodgeBlock.md#dodge-block-duration-increases-with-ping

Also, this issue is present on any version of UT99, and wasn't introduced in any of the 469 patches.

Thanks!

PS: you can find me on Discord under the name Fulcrum / Riverside.

**Comment by Mellesp** [comment]
These are some very interesting findings on an online play issue since the earliest versions of UT.

Using the DodgeClickTimer variable and DodgeDir states I have visualized the mentioned issue:
https://streamable.com/a9zn0z
You can see when on higher ping there's a stutter to the "loading bar". This shows that the variable DodgeClickTimer gets reset multiple times.

**Comment by Mellesp** [comment]
On top of that, I would like to demonstrate another issue with dodging in online play:
https://streamable.com/z4435v

Apparently due to ping a player is not able to dodge directly after landing.
Similar as to the other issue mentioned, this has been in the game since the earliest version of UT.
This bug probably has a different cause. Let me know if it needs to be put in another issue here on GitHub.
