### ISSUE TITLE
[469a] Cluster3D - double taunt sounds

### ISSUE THREAD

**Issue by Chamberly** [OldUnreal/UnrealTournamentPatches#86]
Posting for Old UT Veteran from UT99.org as he is having verification issue getting on Github.

> Taunts coming from players/bots that use the skaarj audio commands/taunts result in 2 audio tracks being played. Ex. Player (skaarj hybrid skin) taunts "Boom!", and a male soldier voice also plays over the skaarj sound (both at the same time). Issue only happens over Cluster3D - not sure how widely it is used but guess its worth mentioning.
I do have a video for proof if necessary. Thanks for the support.

OS: Windows

**Comment by stijn-volckaert** [comment]
A video would be helpful. I'm not sure how to play these Skaarj taunts.

**Comment by dizzy-egg** [comment]
@stijn-volckaert Apparently Skaarj Hybrid models (and presumably voices?) were a part of [Bonus Pack 1](https://unreal.fandom.com/wiki/Bonus_content#Unreal_Tournament). 

Not sure if the voice is actually a separate voice pack, because it's just Male2 voice slowed down by 50%.

You can hear how it's supposed to sound in [this video](https://youtu.be/fEv6IB2TRAQ?t=476). 

With this Cluster3D bug, it sounds like that but the Male2 taunt also plays at the same time, creating a weird echo effect.

**Comment by stijn-volckaert** [comment]
Consistent with a couple of other places in the original code, the taunt was indeed playing twice at the same time. The problem was that Cluster forgot to apply the pitch change to one of the two taunts, which meant that you could hear the Skaarj and Male voices playing simultaneously. We fixed this for 469b.
