### ISSUE TITLE
[469c-RC2] Delay when changing brightness

### ISSUE THREAD

**Issue by unrealtitle99** [OldUnreal/UnrealTournamentPatches#958]
Changing the brightness using the F11 key, when using the OpenGL renderer, results in a short (<0.5s?) delay.

This did not happen with 436.

**Comment by stijn-volckaert** [comment]
Confirmed, but this is not something we're going to fix. 469c has a completely revamped OpenGLDrv. Its default brightness and gamma correction method is very different from what 436's OpenGLDrv did. You can still switch back to the old behavior by setting ```
ColorCorrectionMode=UseGammaRamp
```

in the [OpenGLDrv.OpenGLRenderDevice] section of your game in. This mode is not the default because it does not work well (if at all) on modern systems.
