### ISSUE TITLE
make winXP variant for stable release, plz.

### ISSUE THREAD

**Issue by z0hm** [OldUnreal/UnrealTournamentPatches#995]
subj + latest OpenAL.dll, tnx.

**Comment by stijn-volckaert** [comment]
We've decided to drop support for Windows XP for several reasons:
* Microsoft deprecated support for Windows XP in Visual Studio 2019. We use Visual Studio 2022 for 469c. The old Visual Studio 2017 XP toolset is still available, but its quality seems to be deteriorating with every visual studio update. We've been hit by several game-breaking bugs that were the result of updates in the Visual Studio 2015/2017 XP toolsets
* We have several 3rd party dependencies that either never worked on XP or that dropped XP support years ago
* We have a fair amount of modern C++ code that simply won't compile with the Visual Studio 2015/2017 XP toolsets
* In the four years that have passed since we took over maintenance of the UT99 code base, we haven't had a single active tester on Windows XP
